### ISSUE TITLE
How to use with Editor

### ISSUE THREAD

**Issue by ashl1** [DataTables/Buttons#1]
I cannot find the initialization to work with Editor (instead of TableTools)

**Comment by DataTables** [comment]
This is unreleased software and the documentation hasn't been fully written for it yet, which will be why you can't find it.

**Comment by ashl1** [comment]
I came here from https://github.com/DataTables/ColVis/issues/41#issuecomment-125873876
As I understand, the current published version of Editor doesn't support this Buttons in any way, does it? As I'm closely working on DT now, I just want to test the Buttons on real cases and different circumstances.

**Comment by DataTables** [comment]
I should have stated in my comment there that this is prerelease software that not intended for general consumption yet. Editor 1.5 will feature full support for Buttons when it is released. It is possible to use Buttons with 1.4 but you would need to create your own button configurations.

In the mean time I'm going to close this bug. The initialisation will be fully documented when it and Editor 1.5 are available.
