### ISSUE TITLE
Column visibility + Export buttons

### ISSUE THREAD

**Issue by maslianok** [DataTables/Buttons#10]
If I hide some columns with help of Column visibility button, they should not appear in exported files.

**Comment by maslianok** [comment]
Well, I found that I can do something like this:
```javascript
{
  'extend' => 'pdf',
  'columns' => ':visible'
  'exportOptions' => [
    'columns' => ':visible'
  ]
}
```
But, please, add some examples with this feature, because I spent couple of hours trying to add this behaviour :)

**Comment by DataTables** [comment]
Just:

```js
{
  'extend' => 'pdf',
  'exportOptions' => {
    'columns' => ':visible'
  }
}
```

Should do it.

The [third example on the reference page for the button](http://datatables.net/reference/button/pdfHtml5#Examples) shows something similar, but I think it would be a good example this one. [I've added one here](https://github.com/DataTables/Buttons/commit/2f49b95e034d8d6).
