### ISSUE TITLE
colvis columns callback missing data

### ISSUE THREAD

**Issue by legshooter** [DataTables/Buttons#102]
Unlike other buttons, colvis' columns callback has empty data, which makes it difficult to use class based selectors.

Instead of doing what I do for most buttons:

``` javascript
extend: 'colvis',
columns: ':not(.control):not(.select-checkbox)'
```

I have to resort to:

``` javascript
extend: 'colvis',
columns: 'gt(1)'
```

I understood why when I saw that:

``` javascript
extend: 'colvis',
columns: function ( idx, data, node ) {
    // console.log(data) = [];
    // console.log(node.outerHTML) = <th></th>
},
```

I do have `className`s defined:

``` javascript
columns: [
    {
        className: 'control',
        // ...
    },
    {
        className: 'select-checkbox',
        // ...
    },
    // ...
]
```

I would much prefer btw to handle all of this by the columns' names instead of their class names, but maybe this is an issue for another time.

**Comment by DataTables** [comment]
> colvis' callback

Which callback are you referring to? The `columns` option as a function?

**Comment by legshooter** [comment]
This one:
```javascript
buttons: [
	{
		extend: 'colvis',
		columns: ':gt(0)'
	}
]
```
https://datatables.net/reference/button/colvis

**Comment by DataTables** [comment]
Can you give me a link to an example showing the issue (JSFiddle, JSBin, CodePen, whatever). I'm not quite getting it I'm afraid.

**Comment by legshooter** [comment]
I meant that a class based selector (such as  `:not(.control):not(.select-checkbox)` in my case) doesn't work on the `columns` property of a `button` object when I extend `colvis`. That's about it.

The rest of the above is just how I realized *why* you can't do that.
___

**Although there is one critical correction to make:**
When I wrote it works for other buttons such as `copy`, `csv` etc. I was actually referring to their `exportOptions.columns` property.

i.e. This works great:
```javascript
buttons: [
    {
        name: 'print',
        extend: 'print',
        exportOptions: {
            columns: ':visible:not(.control):not(.select-checkbox)'
        }
    },
    {
        name: 'copy',
        extend: 'copy',
        exportOptions: {
            columns: ':visible:not(.control):not(.select-checkbox)'
        }
    },
    {
        name: 'csv',
        extend: 'csv',
        exportOptions: {
            columns: ':visible:not(.control):not(.select-checkbox)'
        }
    }
]
```

This does not:
```javascript
buttons: [
    {
        name: 'colvis',
        extend: 'colvis',
        columns: ':visible:not(.control):not(.select-checkbox)'
    }
]
```
But this does(!):
```javascript
buttons: [
    {
        name: 'colvis',
        extend: 'colvis',
        columns: ':gt(1)'
    }
]
```

Hopefully this all makes sense now? Sorry if my explanations are somewhat convoluted.

**Comment by DataTables** [comment]
I see what you mean - thanks! The problem here is that the Buttons are being created _before_ the columns in the table - hence why the class selector doesn't work for the colvis button type - it is created when Buttons is built, but the export buttons only need to access the columns when they are activated.

As a workaround you could use [`button().add()`](https://datatables.net/reference/api/button().add()) to add the colvis button after initialisation.

**Comment by legshooter** [comment]
Ohh.. I see, makes sense.

Too bad though, I am setting defaults as a base for all the reporting tables I am instantiating throughout my app, and I want everything to be centralized in that object in an orderly fashion, for saner maintenance as time goes by. Not sure if spreading button instantiations all over the place would result in more hair on my head in the future, in comparison to relying on column order. But that's for me to figure out I guess.

Thanks a lot!

**Comment by DataTables** [comment]
This was [fixed in DataTables core](https://github.com/DataTables/DataTablesSrc/commit/1d6baac32f3e84a6cd25c8001c2903ade40b10e3). The 1.10.16 release will include the change, or the nightly version already does until then.

**Comment by brenjt** [comment]
@legshooter A temporary work around could be setting your columns in another variable:

```
var columns = [
    {data: 'id', title: 'ID', className: 'no-toggle'},
    {data: 'name', title: 'Name'},
];
```

And then in your button config:

```
{
   extend: 'colvis',
   columns: function (idx, data, node) {
      return typeof columns[idx] !== 'undefined' && (!columns[idx].className || columns[idx].className !== 'no-toggle');
   },
   postfixButtons: [ 'colvisRestore' ]
}
```
