### ISSUE TITLE
Colvis button style for hover and focus looks the same as the active style

### ISSUE THREAD

**Issue by DaveSenn** [DataTables/Buttons#107]
The style for hover and focus of the Colvis buttons/items (column selection) looks like the style of the TWBS active class (applied to selected columns).
Why this is a problem:
When the user deselects a column using the Colvis button, the item representing the deselected column still looks like it is selected (because it has focus)… The user therefore thinks the column is still selected.

Possible solution:
Changing the hover and focus style so it does not look the same anymore.
![screen](https://cloud.githubusercontent.com/assets/7510324/20246295/0bf04186-a9b4-11e6-80b3-666221f078c1.gif)

**Comment by DataTables** [comment]
[In this example](https://www.datatables.net/extensions/buttons/examples/styling/bootstrap.html) the hover style with standard bootstrap is just a slight grey. Are you using a custom styling to get the blue highlight? Or am I missing something in mine :-)

**Comment by DaveSenn** [comment]
You’re right. I assumed bootstrap use blue as hover/focus background-color, because my browser said that the style comes from bootstrap.css.
And in fact the style is form bootstrap (dropdown.less).. but the problem was caused by another less file which changed the _@dropdown-link-hover-bg_ variable to _#3276B1_.

```
.dropdown-menu > li > a {
  &:hover,
  &:focus {
    text-decoration: none;
    color: @dropdown-link-hover-color;
    background-color: @dropdown-link-hover-bg; // TWBS value: #f5f5f5.. was set to #3276B1
  }
}
```
Consider the “issue” as closed.
Andy sorry for the wrong report.

**Comment by DataTables** [comment]
No worries - thanks for following up!
