### ISSUE TITLE
Problem with exportData on selected:true in last release 1.2.3

### ISSUE THREAD

**Issue by dokamo** [DataTables/Buttons#108]
When upgrading from 1.2.2 to 1.2.3 on CDN, exportData does not match selected true rows. 
Just changing to 1.2.2 it works as expected.

console.log(datatable.buttons.exportData({modifier:{selected:undefined}}))
console.log(datatable.buttons.exportData({modifier:{selected:false}}))
console.log(datatable.buttons.exportData({modifier:{selected:true}}))

>> Object {header: Array[8], footer: null, body: Array[100]}
>> Object {header: Array[8], footer: null, body: Array[99]}
>> Object {header: Array[8], footer: null, body: Array[0]}

1.2.2
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.12/b-1.2.2/b-colvis-1.2.2/b-html5-1.2.2/b-print-1.2.2/fc-3.2.2/fh-3.1.2/r-2.1.0/rr-1.1.2/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

1.2.3
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/jszip-2.5.0/pdfmake-0.1.18/dt-1.10.13/b-1.2.3/b-colvis-1.2.3/b-html5-1.2.3/b-print-1.2.3/fc-3.2.2/fh-3.1.2/r-2.1.0/rr-1.2.0/sc-1.4.2/se-1.2.0/datatables.min.js"></script>

**Comment by DataTables** [comment]
Thanks!

I'll probably do a 1.2.4 release next week to push this fix out.

**Comment by DataTables** [comment]
For reference: That is being caused by 767a24918b9ea71d2af3d3620fe47d776a28de5e. The modifier as it is now would only select cells if they were selected (which they typically aren't - rows are).
