### ISSUE TITLE
Table changes are not picked up when using buttons

### ISSUE THREAD

**Issue by wkrick** [DataTables/Buttons#109]
A user can modify a table by ~~filtering or~~ deleting rows, but when the buttons are used, the resulting content always displays the whole table.  This seems like a bug to me.  Wouldn't you want to be able to ~~filter a table~~ delete rows and create, for example, a PDF of just the ~~filtered~~ modified results?

**Edit**: This is using the HTML5 buttons.  Flash is not an option.

**Edit 2**;  Nevermind about the filtering.  That **IS** being picked up.  User error on my part.  It's just deleting rows using the datatables API that doesn't get picked up.

**Comment by DataTables** [comment]
Hi, I saw your post about this in the forums as well, but for completeness here, could you link to a test case showing the issue so it can be debugged?

**Comment by wkrick** [comment]
I made a really simple test case and it works perfectly, so the problem must lie with my real project.  I'm probably doing something wrong.   Sorry for the false alarm.
