### ISSUE TITLE
copyHtml5 - not working in Chrome

### ISSUE THREAD

**Issue by Misiu** [DataTables/Buttons#11]
Hi,
I just checked Buttons example (http://datatables.net/extensions/buttons/examples/html5/simple.html) and on WIn 8.1 Chrome 44 I can't get Copy button to work.
If I open same page in IE11 everything works as expected (after pressing Ctrl + C data is copied to clipboard).
I've inspected that popup dialog in Chrome dev tools and that textbox is empty, when in IE there is text in it.

**Comment by DataTables** [comment]
Hi,

Thanks for posting this. Its an odd one as it seems to sometimes work and sometimes not... However, it reliably works if I run `focus()` before selecting the text to be copied - that has been [committed here](https://github.com/DataTables/Buttons/commit/3f870c0cc85).

I'm going to do a 1.0.1 release of Buttons at the end of the week.
