### ISSUE TITLE
put CDN files to repo

### ISSUE THREAD

**Issue by maruilian11** [DataTables/Buttons#110]
Hi, I'm from [cdnjs](https://github.com/cdnjs/cdnjs). Recently we want to add your lib to https://cdnjs.com.
Could you please consider adding `buttons.dataTables.min.css` and `dataTables.buttons.min.js` to repo?
like [jquery.dataTables.min.css](https://github.com/DataTables/DataTables/blob/master/media/css/jquery.dataTables.min.css) and [jquery.dataTables.min.js](https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.min.js)
So that we can use our git auto-update config to get files from every git tag.
Thank you very much!

https://github.com/cdnjs/cdnjs/issues/10005

**Comment by DataTables** [comment]
Hi,

Thanks for your message. Create to hear you want to include this software on cdnjs.

There is another thread in another one of my repos about this: https://github.com/DataTables/FixedHeader/issues/83 . If you have any questions about my replies there I'd be happy to answer them.

**Comment by maruilian11** [comment]
@DataTables Thank you for your quick reply.
I think we can use this repo to set up our auto-update config. 
https://github.com/DataTables/Dist-DataTables-Buttons/tree/master/js

But there is only `js` files, I saw you provide `buttons.dataTables.min.css` on your site.
Is there other repo providing the css file? 
Or is it possible also put `buttons.dataTables.min.css` to DataTables/Dist-DataTables-Buttons?
Thank you!

**Comment by DataTables** [comment]
Hi,

The `buttons.dataTables.min.css` file is in [Dist-DataTables-Buttons-DataTables](https://github.com/DataTables/Dist-DataTables-Buttons-DataTables).

The "core" distribution repo contains only the base Javascript. Then you use one of the styling repos (`-DataTables`, `-Bootstrap`, etc) to including the styling.

The reason for that was npm. It didn't really provide a way to conditionally select only certain files depending on the style selected.

**Comment by maruilian11** [comment]
@DataTables Because our auto-update config doesn't support the multiple repo function.
Do you mind if we may need to add these files as two libs?

**Comment by DataTables** [comment]
> Do you mind if we may need to add these files as two libs?

I'm afraid I don't really understand what that means?

However, I do see how this multiple repo setup can be a bit of a pain for you! I will look into providing the minified files in this repo in the new year.

**Comment by maruilian11** [comment]
@DataTables thank you, let will help us a lot!
If you decide not to provide the files, just tag us, we will handle this problem ourself. :)

**Comment by kant2002** [comment]
@DataTables did you put files in the repo? CDNjs still missing datatable buttons. Would be good if somebody from CDNjs finally put library in their CDN

**Comment by DataTables** [comment]
The files to use on the CDN are [in this repo](https://github.com/DataTables/Dist-DataTables-Buttons). There are a number of styling repos such as [the DataTables one](https://github.com/DataTables/Dist-DataTables-Buttons-DataTables) and [Bootstrap4 one](https://github.com/DataTables/Dist-DataTables-Buttons-Bootstrap4) which should also be used.

**Comment by kant2002** [comment]
@DataTables so I assume that I should ping somebody from CDNjs team, so they do what needed on their side. Is this correct?

**Comment by AllanJard** [comment]
This is a really old issue now - I never followed up at the time - sorry! Buttons can be found on CDNJS here: https://cdnjs.com/libraries/datatables.net-buttons .
