### ISSUE TITLE
[Feature Req] Export Empty cells

### ISSUE THREAD

**Issue by cwolcott** [DataTables/Buttons#112]
Could you allow a customize option to export empty cells? The reason is if empty cells are not exported a style can not be applied because there is no cell definition. I would like to put a thin border around column B, but because cell B177 isn't defined the style will not be applied to B177 and any other empty cell in column B. Thus when you look at the excel spreadsheet it looks odd.

The current code (buttons.html5.js line 1040) skips over any null, undefined or blank cells.
```
// For null, undefined of blank cell, continue so it doesn't create the _createNode
if ( row[i] === null || row[i] === undefined || row[i] === '' ) {
    continue;
}
```

New code
```
// For null, undefined of blank cell, determine customize config to exportEmptyCells
if (row[i] === null || row[i] === undefined || row[i] === '') {
    if (config.exportEmptyCells) {
        cell = _createNode(rels, 'c', {
            attr: {
                r: cellId
            }
        });
        rowNode.appendChild(cell);
    }
    continue;
}
```

**Comment by DataTables** [comment]
Going to close this discussion in favour of your thread [in the forums](https://www.datatables.net/forums/discussion/39765/export-empty-cells#latest) rather than trying to track it in two different places.
