### ISSUE TITLE
Avoid export removing "0" at the beginning  of "numeric string"

### ISSUE THREAD

**Issue by equapro** [DataTables/Buttons#113]
I'm facing a problem to export a "numeric string" starting with "0" (for example zip code).

Take a look to https://jsfiddle.net/equapro/0zm9kobq/
Nice (06000) and Singapore (050335) zip code are exporting like numeric values
`<c r="..." s="..."><v>06000</v></c>`

Spreadsheet applications, remove the "0" at the beginning of those cells.

Those kind of strings are not real numeric values. 

It's possible to exclude them with a little hack: 
https://github.com/equapro/Buttons/commit/13db153b9ff9612939b859bc704ecd37c67310e8

**Comment by DataTables** [comment]
Thanks. Its being caused by the [special output](https://github.com/DataTables/Buttons/blob/08c6289a26d99d91975da583a389cdc5df81338d/js/buttons.html5.js#L796). The regular expressions for those need to be updated to exclude numbers with a leading 0.
