### ISSUE TITLE
Excel column width does not cap at 40 characters

### ISSUE THREAD

**Issue by SpliceVW** [DataTables/Buttons#117]
The documentation for excelHtml5 states that the column width maximum is 40. The actual maximum width is the string length of the first column with a width greater than 40 characters multiplied by 1.3 (or 255 characters, Excel's maximum).

https://jsfiddle.net/SpliceVW/urk14nmr/3/

**Comment by DataTables** [comment]
Thank you! That was one of my dafter programming mistakes...

[Fix committed](fa0a7d875e5732dd6585aaddfa450b076186821d) (using 52 as the max width now - 40*1.3) and it will be in the next release.
