### ISSUE TITLE
Add option to specify ID attribute

### ISSUE THREAD

**Issue by manderson23** [DataTables/Buttons#121]
It is useful to give buttons an ID for automated testing tools.

At the moment to set an attribute on buttons you need to use an init function.

It would be useful if there was a simple id option that could be used.

**Comment by DataTables** [comment]
More generally it will probably be useful to just have an `attr` option for the buttons which is an object that contains attribute name / value pairs (including id). Then it can be used for anything.

Good idea - thanks for this.
