### ISSUE TITLE
Complex headers in exports

### ISSUE THREAD

**Issue by omsiqveland** [DataTables/Buttons#124]
Complex headers containing multiple rows and columns with varying colspan does not show up in exports.
It would be great if we got an exported version of the table containing all information in the table. Currently, only my last header row shows up.

The colspan in .csv issue could be solved by appending empty cells, or by adding the same (content-holding) cell _"colspan"_ times for instance.

**Comment by donnykurnia** [comment]
@omsiqveland I have open PR #123 that you can try (only for print for now). I'll try to have time to make this also works for excel and pdf export.

@DataTables when can you review my pull request?

**Comment by DataTables** [comment]
Sorry for the delay! I'm wrapped up in things at the moment, but I've got the PR e-mail in my inbox to make sure I do get to it.

**Comment by DataTables** [comment]
Closing in favour of #123.
