### ISSUE TITLE
how to enable pdf Button

### ISSUE THREAD

**Issue by hemnath11** [DataTables/Buttons#125]
this.dtOptions = {
      ajax: 'assets/data.json',
      columns: [{
        title: 'ID',
        data: 'id'
      }, {
        title: 'First name',
        data: 'firstName'
      }, {
        title: 'Last name',
        data: 'lastName'
      }],
      // Declare the use of the extension in the dom parameter
      dom: 'Bfrtip',
      // Configure the buttons
      buttons: [
        'copy',
        'print',
        'excel',
        'pdf'                
      ]
    };
i'm using this sample but pdf button not appear on the data table using angular

**Comment by DataTables** [comment]
Could you post support requests in the [DataTables forums](//datatables.net/forums) as the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) and the new issue template text states. I'm sorry if that document wasn't clear enough on that topic.

Please also be sure to include a link to a test case showing the issue so it can be debugged.

In this case my guess is that pdfmake is not being loaded, but I don't know without a test case.
