### ISSUE TITLE
Bootstrap integration on site

### ISSUE THREAD

**Issue by Misiu** [DataTables/Buttons#13]
When viewing example of Buttons plugin with Bootstrap 3 integration (http://datatables.net/extensions/buttons/examples/styling/bootstrap.html) I noticed that buttons aren't styled correctly.
I get this:
![snap 2015-08-20 at 15 47 08](https://cloud.githubusercontent.com/assets/1741838/9384960/0228653e-4754-11e5-9403-a0e8c8244ae9.png)

When I think this should be result:

![snap 2015-08-20 at 15 51 13](https://cloud.githubusercontent.com/assets/1741838/9384974/10a86a46-4754-11e5-9b20-d451cdc509c6.png)

Problem occurs in http://datatables.net/media/css/site-examples.css file, that is overriding default Bootstrap style, maybe this can be fixed to show integration correctly?

Also there is small CSS bug: distance between table and buttons  and between table and search input is different.

**Comment by DataTables** [comment]
Thank you - yes, that is a bug with the css for the site conflicting with Bootstrap. I'll look into what I can do about that.

**Comment by DataTables** [comment]
Now fixes with the latest deployment to the site.

**Comment by Misiu** [comment]
works fine, thank You :smile:
