### ISSUE TITLE
Accessibility: Collections don't work without CSS

### ISSUE THREAD

**Issue by Jamstah** [DataTables/Buttons#130]
When using buttons, if you turn off CSS, collections don't work. This is a problem for accessibility, where CSS is often not available.

**Comment by DataTables** [comment]
Any thoughts on what to do about this? I'm drawing a bit of a blank to be honest.

**Comment by Jamstah** [comment]
I did have a quick look, but there are a number of issues I think.

First up, we would want to move the popup containers from being attached to body to being placed just after the button. Maybe in a ul? Then make sure they are hidden with css. When the css is disabled they will then appear in the right place for context.

From there, I think the rest of the solution should fall into place more easily with whatever needs to be done to fix problems caused by moving the popup containers.

I got as far as moving the containers, but don't know the code well enough to get further without a lot of learning about the code base, so I thought I'd open an issue and see if you had better ideas :)

**Comment by DataTables** [comment]
Thanks for the feedback on that. So would you suggest not having it attach itself and remove itself from the DOM as it currently does, but just always have it in the document?

**Comment by Jamstah** [comment]
I think that would help, or at least attach it to the right point in the dom instead of at the end of the body.
That way, when css is disabled, the collection buttons will appear in the right place.

Taking a look at the ARIA doc:
- aria-haspopup should be true on the collection buttons: myBrowserhttps://www.w3.org/TR/wai-aria/states_and_properties#aria-haspopup
- aria-owns could be used to identify that popup if it isn't a DOM descendant, otherwise rely on it being a DOM descendant. https://www.w3.org/TR/wai-aria/states_and_properties#aria-owns

It would probably also make sense to use the <button> element instead of the <a> element to properly indicate intent (doesn't navigate) and automatically have a tabindex: https://marcysutton.com/links-vs-buttons-in-modern-web-applications/

**Comment by DataTables** [comment]
Fantastic - thanks for the pointers. I've made a few changes that should help improve accessibility based on your points above. I'll tag Buttons 1.5.0 with these changes shortly.
