### ISSUE TITLE
Flash buttons don't work unless online

### ISSUE THREAD

**Issue by Worthy7** [DataTables/Buttons#134]
https://github.com/DataTables/Buttons/blob/698d2738b4a1d67c48772d5dffe6da974f4d59fc/js/buttons.flash.js#L1081

This line means that internet is required for flash buttons to work.
I'm not sure how, but can we either make it very clear in the instructions that developers need to change this line to match a copy of `flashexport.swf` on their server, or have some way for this to autodetect (I don't know how)

It took me way too long to figure out why some of our users couldn't export

**Comment by DataTables** [comment]
[This example](https://www.datatables.net/extensions/buttons/examples/flash/swfPath.html) demonstrates how the SWF path location can be changed to wherever you want to store the SWF file for your project.

**Comment by Worthy7** [comment]
I missed that. I didn't even anticipate that it was necessary. Perhaps a line in the normal flash example "The necessary flash is called via CDN, if you want to change this location, see the example here"

**Comment by DataTables** [comment]
Yup - good idea - thanks! I've added it in and will push it out to the site shortly.
