### ISSUE TITLE
How can I add a list of button actions to each row that will not be included in the file exports.

### ISSUE THREAD

**Issue by jayzyaj** [DataTables/Buttons#135]
I am new in using datatables exportable. I want to have an button such as view edit or delete or achive for a specific row. How can I do that? Each time I tried to create a button in the right part of the column is included also in the top file export. But how can I add a button to the right part of the table that will not be placed at the top and not included in the file export?

Here is the sample that I did below.

![123](https://user-images.githubusercontent.com/30188236/31009061-c6c066e6-a538-11e7-8b38-1235c659629e.PNG)

As you can see in the picture the group of buttons has also printed 4 rows for a specific row using bootstrap. But how can I place it in the right corner of the table correctly? Sorry for this question but can someone help me to achieve that?

Appreciate if someone can help.
Thanks in advance.

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the Contributing document, please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.

You might be interested in [this example](https://editor.datatables.net/examples/simple/inTableControls.html) which shows how to make inline editing controls with Editor.
