### ISSUE TITLE
chrome, opera browsers print reopen issue

### ISSUE THREAD

**Issue by saravanan-k90** [DataTables/Buttons#139]
https://github.com/DataTables/Buttons/blob/0d2d8eb6bfb823cf783472edcb455daf8f588aa8/js/buttons.print.js#L161

In chrome and opera.. setTimeout print works first time, the next time it will work only upon switching to parent tab. It has to be changed to `win.setTimeout`.

Sorry I would have submitted a pull request but I have personal system issues, so I am just opening it as an issue.

**Comment by DataTables** [comment]
Awesome - thank you! It will be in the next release.
