### ISSUE TITLE
_filename is broken when setting a custom flashExport path

### ISSUE THREAD

**Issue by Worthy7** [DataTables/Buttons#144]
![image](https://user-images.githubusercontent.com/4762399/37637223-ca529188-2c49-11e8-967d-16511db5cbbb.png)

It says that `_filename is not defined`.

Try this page on IE8:
https://datatables.net/extensions/buttons/examples/flash/swfPath.html

This only seems to happen if `$.fn.dataTable.Buttons.swfPath = '../../swf/flashExport.swf';` is redefined.

**Comment by DataTables** [comment]
Thanks! Fixed in 332ceabac925c496a71a19c381589770d5da0248.
