### ISSUE TITLE
excel export broken in IE

### ISSUE THREAD

**Issue by Worthy7** [DataTables/Buttons#151]
https://datatables.net/extensions/buttons/examples/initialisation/export.html
Go here with IE so it uses the flash buttons. The excel exports, but is broken.

I am going to guess that it is to do with corrupt encoded of the xl/styles.xml, caused by perhaps minification of the flash script.

**Comment by Worthy7** [comment]
/xl/worksheets/sheet1.xml col 791

置き換えられたパーツ: /xl/worksheets/sheet1.xml パーツに XML エラーがありました。  修飾名にはコロンを複数使用できません。場所は、行 1、列 791 です。

It says you cannot have multiple colons in the name.
`<t xmlns:NS1="" NS1:xml:space="preserve">DataTables example - File export</t>`
Seems the flash version is not producing the correct names on the xml.

The html5 version:
`<t xml:space="preserve">DataTables example - File export</t>:

**Comment by Worthy7** [comment]
Sorry, this is not the flash version, I was using IE 11, which should work and use the HTML5 buttons. 

So this is an issue with the HTML5 export, in IE11.

**Comment by DataTables** [comment]
This should have been fixed by 363c2025616f8f8f3729af0ab945501e2518f2c5. Have you used the latest nightly, or just the release version? The release version doesn't include this fix yet and there are a number of discussions about it in the forum.

**Comment by Worthy7** [comment]
@DataTables  _Coming this week. For certain this time._ -- 18th August lol

Can you release it please :)

**Comment by DataTables** [comment]
Yeah. Unfortunately the amount of support requests has been overwhelming recently. I am working on it and various other things. It is coming. I'm going to stop putting dates on things :-)

**Comment by Worthy7** [comment]
@DataTables Fail enough. Support is your paycheque so I understand.

**Comment by DataTables** [comment]
Working on the release and closing stuff off for it just now. Closing this as such.
