### ISSUE TITLE
Flash buttons broken

### ISSUE THREAD

**Issue by Worthy7** [DataTables/Buttons#153]
Flash buttons don't work in any IE
https://datatables.net/extensions/buttons/examples/flash/simple.html

**Comment by DataTables** [comment]
That did help - thanks. I started debugging Flash and that massively wasn't easy, so diff'ed 1.4.2 and 1.5.0 and found it was [this commit](https://github.com/DataTables/Buttons/commit/4b2718099380f710affaa6aa29dcbd3812fb6bba) that caused the issue in IE (good grief!).

I've added a check in the code to see if the browser is IE. If so then `<a>` is used as the tag for the button. In modern browsers `<button>` is used.
