### ISSUE TITLE
[Bug] with Colvis button when columns are reordered with ColReorder

### ISSUE THREAD

**Issue by Xima** [DataTables/Buttons#154]
Issue: After reordering columns (when a column is hidden), the order in the ColVis dropdown menu is not updated properly and result in the wrong column being hidden/visible.

For example here [https://jsfiddle.net/djap4qm1/](https://jsfiddle.net/djap4qm1/)
To reproduce the bug : 
Hide column Position, slide Age before Office. Now hiding Office will actually hide Age

The issue is with Button extension version 1.5.4. 
There is no issues with version 1.5.2 as seen in this example : [https://jsfiddle.net/hengdv29/1/](https://jsfiddle.net/hengdv29/1/)

**Comment by sclark2006** [comment]
I solved it by, in addition to implementing the solution that @vonboth said, by inserting this.active(curr) in the line 98. That is, activating the column with previous col.visible() value in the action function.

**Comment by creamteam-de** [comment]
is there a plan to merge this PR? We are affected for the bug. Thanks!

**Comment by DataTables** [comment]
Its actually already fixed in the latest versions of Buttons and ColReorder: https://jsfiddle.net/n4oe7dqx/ . Sorry - I forgot to close this PR off.
