### ISSUE TITLE
Bug with collections without background: re-clicking the trigger button immediatly closes the collection again

### ISSUE THREAD

**Issue by GillesVermeulen** [DataTables/Buttons#155]
When using a button collection without a full screen CSS background, you can just click the collection-trigger button again, and this causes unwanted behavior: The collection will fade in and immediately fade out again.

[Here is an example in codepen](https://codepen.io/anon/pen/QJEKry)

The reason is that the click listener on the body gets triggered as well as the click listener on the collection button, and the click listener on the body will close the collection.

Possible solution:
Check in the click listener of the collection button if the collection is not already open (and then close it and remove the body listener)

**Comment by DataTables** [comment]
Good point - thanks for letting me know about that.

**Comment by GillesVermeulen** [comment]
In a related issue: when one collection is open, and you click on another collection button, the background of the second collection also fades in and immediately fades out again.

**Comment by stephanvierkant** [comment]
Related to this issue?

https://datatables.net/forums/discussion/56188/bug-button-collection-doesnt-work#latest

**Comment by AllanJard** [comment]
Doesn't appear to be [an issue with the latest](https://codepen.io/DataTables/pen/RwEXZjy). I guess I fixed this at some point and forgot to close it, sorry.
