### ISSUE TITLE
Export Loading Option

### ISSUE THREAD

**Issue by jnreynoso** [DataTables/Buttons#158]
The button of export data is blocking, is not posible for me adding styles or change classNames, for create effect of loading, I tried modify the library, take export function to a serviceWorker, but don't access to variables necessaries for export function.

Thanks.

**Comment by Adondriel** [comment]
If you want to do this, delay the actual click event of the button for like, 500ms before actually calling the button, and before the button is called, add the loading styles, and it should work.

**Comment by AllanJard** [comment]
I've introduced a new `async` option for the buttons that effectively do this. [Commit here](https://github.com/DataTables/Buttons/commit/55da318033557d199d1730a03149bca210ed5955). It will be in Buttons 3.
