### ISSUE TITLE
Repair autoFilter, false option not work

### ISSUE THREAD

**Issue by ilysamo** [DataTables/Buttons#160]
Please, change our code (buttons.html5.js) from this:

		// Auto filter for columns
			$('mergeCells', rels).before(_createNode(rels, 'autoFilter', {
				attr: {
					ref: 'A' + dataStartRow + ':' + createCellPos(data.header.length - 1) + dataEndRow
				}
			}));

To this:

		// Auto filter for columns
		if (config.autoFilter) {
			$('mergeCells', rels).before(_createNode(rels, 'autoFilter', {
				attr: {
					ref: 'A' + dataStartRow + ':' + createCellPos(data.header.length - 1) + dataEndRow
				}
			}));
		}

**Comment by DataTables** [comment]
Thank you!
