### ISSUE TITLE
stripHtml not working properly on individual column searching with select inputs

### ISSUE THREAD

**Issue by simaosoares** [DataTables/Buttons#163]
Hello everyone.

I added individual column searching to a datatable and when exporting the data to excel file the column names are extracted wrongly if the header contains filters with select input.
The problem is on function **stripHtml** located in file **dataTables.buttons.js**.
The regex does not work properly with **select** tags.

A test case can be found on the link below:

**https://jsfiddle.net/simaosoares/8m5pqfde/**

I ended up extracting the column names manually with custom format. 
Maybe another regex could be used instead or another way of extracting.

**Comment by DataTables** [comment]
This is the problem in using regex to extract HTML. It is _far_ from perfect. But doing it properly with DOM parsing is slow. I currently don't have any plans to change it, but if anyone has any suggestions for a fast way to do it, that would be most welcome.

**Comment by AllanJard** [comment]
Closing as stale. Use the `body` formatter option for the export data which gives access to the HTML elements and can be used on a case by case basis. It could be that we should auto detect <select> data and get the selected option. I'm concerned about the performance impact though.
