### ISSUE TITLE
Popover from "colvis" outside window

### ISSUE THREAD

**Issue by kirilmitev** [DataTables/Buttons#168]
When clicking the "colvis"-button an absolute positioned popover-block gets created and rendered in DOM. While initialising this popover-block, the code checks if there is enough space on the screen to render it, and if not, the popover-block gets moved, so that it fits. This is done in "dataTables.buttons.js" on line 1044:
 
> // Right alignment to window
> var listOffsetRight = hostNode.offset().left + collectionWidth;
> if ( listOffsetRight > $(window).width() ) {
>       ...
> }

with 

> var collectionWidth = display.outerWidth();

In v1.6.0 this is working as expected, but in v1.6.1 it is not. This is because in v1.6.1 `display` gets hidden earlier on line 992:

> display
> .addClass( options.collectionLayout )
> .css( 'display', 'none' )

Because the element is hidden, it's outerWidth() is 0 and the further calculations are incorrect.
Please fix this!

**Comment by AllanJard** [comment]
I missed this one at the time - so sorry! This whole section of Buttons has been rewritten and I've not encountered the issue described recently. Going to close this as stale. If still and issue please reopen with a test case.
