### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by Theolodewijk** [DataTables/Buttons#172]
composer require datatables/buttons

  [InvalidArgumentException]
  Could not find a matching version of package datatables/buttons. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by Theolodewijk** [comment]
I like do use composer to download this an get updates

**Comment by DataTables** [comment]
We don't currently support composer as a package manager - sorry. Currently npm is our main one and we are planning to add Nuget support in future.

**Comment by Theolodewijk** [comment]
whay not composer ?

**Comment by Theolodewijk** [comment]
can you also simply download updates with npm and have conjob updated and if there is a new version from behind the public folder to public volder copy?

**Comment by DataTables** [comment]
We've not had many requests for composer support, so it hasn't been a priority for us I'm afraid (also we don't use it ourselves).

We'd welcome a pull request to all our distribution repos if it is something you would be willing to support:

* https://github.com/DataTables/Dist-DataTables-Buttons
* https://github.com/DataTables/Dist-DataTables-Buttons-DataTables
* https://github.com/DataTables/Dist-DataTables-Buttons-Bootstrap4
etc

Allan

**Comment by Theolodewijk** [comment]
On a CentOS 8 server with Directadmin and Nginx npm and bower wil not work.

A pity that you limit the use of Datatables to yourself and that everyone has to download it manually every time to stay up to date!

**Comment by DataTables** [comment]
Its not limited at all. Its open source under the MIT license. We haven't made it available via composer - but we might in future, or as I say, we would take pull requests to add support for that one specific package manager.

**Comment by Theolodewijk** [comment]
it is limited if you cannot simply update easily where milienen systems use composer to perform such updates and I have to do everything to be able to perform such updates automatically.

**Comment by Theolodewijk** [comment]
For users who want use composer I have a workaround use composer and git

composer.json
`{
    "require": {
        "datatables/datatables": "^1.10"
    },
    "scripts": {
        "post-update-cmd": [
            "rm -rf public_html/DataTables/latest",
            "cp -R vendor/datatables/datatables/media/ public_html/DataTables/latest",
            "rm -rf git/Dist-DataTables-Buttons",
            "rm -rf public_html/Dist-DataTables-Buttons/latest/js/",
            "git clone https://github.com/DataTables/Dist-DataTables-Buttons git/Dist-DataTables-Buttons",
            "cp -R git/Dist-DataTables-Buttons/js/ public_html/Dist-DataTables-Buttons/latest/js"
        ]
    }
}`

Thanks for the quick replay

**Comment by DataTables** [comment]
Thanks for posting that!
