### ISSUE TITLE
1.6.2 update breaks colvis button container opening position

### ISSUE THREAD

**Issue by hadithmv** [DataTables/Buttons#174]
The 1.6.2 update makes the button container to be opened forced to the left, even if the colvis button is elsewhere.

While the old 1.6.1 version opens as expected, container opens wherever colvis happens to be.

Example of said error: http://live.datatables.net/limotodi/1/edit

@DataTables

**Comment by SandyDatatables** [comment]
Hi,

An oversight on our part, sorry about that. I've added a check to see if the buttons container is floating right, and if so the popover will also align right.

Please take a look at [this commit](https://github.com/DataTables/Buttons/commit/71d5b0c780f448422a66735b8d3669bd58395c4c). It is also now working in [this copy](http://live.datatables.net/quhisuhe/1/edit) of your example.

**Comment by hadithmv** [comment]
Unfortunately, this does not resolve the issue.

Its just a fix for when the button container floats right.

The float right was only meant to be one example of how the popover does not follow the container, which it still doesn't in all other cases.

Various examples shown here: http://live.datatables.net/ficamogo/1/edit

@SandyDatatables

**Comment by SandyDatatables** [comment]
Ok yes fair points.

Please see [this commit](master b5d0133).

And find it working in [your examples](http://live.datatables.net/punizewe/1/edit).

**Comment by hadithmv** [comment]
Yes, I can confirm this works as expected. Thank you Sandy.
