### ISSUE TITLE
Right alignment of button collections does not work with Bootstrap styling

### ISSUE THREAD

**Issue by prantlf** [DataTables/Buttons#175]
If the right alignment is specified for the dropdown with the button collection, the right side of the dropdown panel should be aligned with the right side of the toggling button. However, the left side of the dropdown panel gets aligned with the right side of the toggling button. It makes the dropdown panel rendered too far in the right direction. If the toggling button is placed on the right side of the window, the dropdown will be rendered even outside of the window.

Example of the configuration:

```js
buttons: [
  {
    extend: 'colvis',
    text: 'Cols',
    align: 'button-right'
  },
  {
    extend: 'collection',
    text: 'Exp',
    align: 'button-right',
    buttons: ['copy', 'print', 'csv', 'excel', 'pdf']
  }
]
```

Output of the [testing page](http://live.datatables.net/hipamana/1/):

![0-out](https://user-images.githubusercontent.com/733193/82667431-26b94880-9c38-11ea-854c-727cd14a4633.png)

Software versions:

```json
{
  "bootstrap": "4.5.0",
  "datatables.net": "1.10.21",
  "datatables.net-bs4": "1.10.21",
  "datatables.net-buttons": "1.6.2",
  "datatables.net-buttons-bs4": "1.6.2",
  "datatables.net-colreorder-bs4": "1.5.2",
  "datatables.net-fixedheader-bs4": "3.1.7"
}
```

**Comment by prantlf** [comment]
It appears, that the width of the dropdown panel is always measured as zero. The quickest workaround is to measure the child `dropdown-menu`, which has the actual width, instead of the parent `dt-button-collection`.

```diff
--- node_modules/datatables.net-buttons/js/dataTables.buttons.js.vendor	2020-05-22 12:22:25.000000000 +0200
+++ node_modules/datatables.net-buttons/js/dataTables.buttons.js	2020-05-22 12:23:28.000000000 +0200
@@ -1073,7 +1073,7 @@
 
 			// Get the size of the popover (left and width - and ...)
 			var popoverLeft = display.offset().left;
-			var popoverWidth = display.width();
+			var popoverWidth = content.width();
 			var popoverRight = popoverLeft + popoverWidth;
 
 			// Get the size of the host buttons (left and width - and ...)
```

```
npm i -D datatables.net-buttons@1.6.2 datatables.net-buttons-bs4@1.6.2
patch -p0 < dataTables.buttons.js.diff
```

The problem and the fixed result for the middle button:

![2-out](https://user-images.githubusercontent.com/733193/82668128-67659180-9c39-11ea-800f-1472b9f8148a.png)
![2-in](https://user-images.githubusercontent.com/733193/82668133-6a608200-9c39-11ea-9205-ffaf9d0ec82f.png)

The problem and the fixed result for the rightmost button:

![3-out](https://user-images.githubusercontent.com/733193/82668149-71879000-9c39-11ea-9b7c-022f7551769e.png)
![3-in](https://user-images.githubusercontent.com/733193/82668154-73515380-9c39-11ea-8def-7e60459905d1.png)

**Comment by SandyDatatables** [comment]
Hi @prantlf ,

Thanks for spotting this. I've made the change that you've suggested above and it appears to have fixed the issue. Please take a look at [this commit](https://github.com/DataTables/Buttons/commit/0c717c6bb14f77d156cf0924443b423728d77ace) for that, and this updated [live page](http://live.datatables.net/xehewuca/1/edit) to show it working.

Thanks,
Sandy
