### ISSUE TITLE
`stripHtml` option fails when attribute contains `>` symbol

### ISSUE THREAD

**Issue by kueblc** [DataTables/Buttons#176]
In our use case, we're using DataTables in conjunction with [Stimulus.js](https://stimulusjs.org/) to provide additional data interactivity. Stimulus uses the HTML5 `data-` attribute to specify actions in the form [`event->controller#method`](https://stimulusjs.org/reference/actions).

After integrating Stimulus we discovered that our exported data contains fragments of HTML despite the `stripHtml` option set.

I've tracked the bug down to this relatively simplistic RegExp:

https://github.com/DataTables/Buttons/blob/d7bececf07a22cb8cf686f965bb5f8363a2bfc13/js/dataTables.buttons.js#L2026-L2028

This RegExp does not cover the case where an HTML tag contains `>` within an attribute.

One option is to extend the RegExp to cover quoted attributes, ie
```
/<([^>'"]*('[^']*'|"[^"]*")?)*>/g
```

However I'm also curious if there is a good reason you do not simply use the `HTMLElement.textContent` property instead of `HTMLElement.innerHTML` when `stripHtml` is specified. This would let the browser take care of all the HTML parsing concerns, rather than trying approximate it with RegExp.

Open to hear your thoughts. Thanks for your time and hard work, and let me know if you'd like a PR for this.

**Comment by DataTables** [comment]
Hi,

|Thanks for the improved regex. Yes, I've over simplified a bit there, and it assumes that `<>` are not used inside an attribute. A PR to address that with your improved regex would be most welcome, or I'm happy to just commit it in myself if you prefer.

We use innerHTML for `decodeEntities` not `stripHTML`. We could combine the two together, but they can also be used independently.

Allan

**Comment by kueblc** [comment]
Thanks Allan!

**Comment by DataTables** [comment]
Hi,

Just to say that I've had to [revert this](https://github.com/DataTables/Buttons/commit/4bd57cdb229606e0a2d8366ad11f5612d73433fa) for the moment. It is giving a recursion error in Firefox:

```
"<select class=\"form-control\" style=\"margin-left:-25px;width: 150%\" \"=\"\"><option value=\"\">Name</option><option value=\"Donna Snider\">Donna Snider</option></select>".replace(/<([^>'"]*('[^']*'|"[^"]*")?)*>/g, '' )
```

**Comment by kueblc** [comment]
Interesting, I have not seen this exception with RegExp before, but indeed I was able to reproduce it with the test case provided. Thanks for the heads up.

We ended up using `.textContent` in our application instead of manually processing `.innerHTML` with `stripHtml`.

I suppose I'm still not sure what the point of `decodeEntities` and `stripHtml` are, since this is just an approximation of what you'd get from `.textContent` for free. That said, you're a lot closer to your user base, so there's probably use cases I'm not thinking of.

**Comment by kueblc** [comment]
Here is how we ended up handling form elements. We only needed support for select and text fields, though it could easily be extended to support other form elements.
```js
    const exportValue = node => {
      // special case for select elements, return current selection text
      let select = node.querySelector('select')
      if (select) {
        return select.options[select.selectedIndex].text
      }
      // special case for input text elements, return value
      let input = node.querySelector('input[type=text]')
      if (input) {
        return input.value
      }
      // otherwise return the text content
      return node.textContent
    }
```

And then used `exportOptions` to apply it to the exported document
```js
    dtOptions.exportOptions = {
      format: {
        body: (data, row, column, node) => exportValue(node).trim().replace(/\n\n+/g, '\n')
      }
    }
```

**Comment by DataTables** [comment]
Yes - textContent would do the job nicely as well, but it means hitting the DOM again rather than using the cached strings, so would slow things down. Using conditions also provides a little more flexibility if you are wanting to output the html.
