### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by BrandonNoad** [DataTables/Buttons#18]
Hi. I see there is an official package for the core library (https://www.npmjs.com/package/datatables). Any plans on publishing npm packages for the Extensions as well?

Cheers

**Comment by DataTables** [comment]
Yes - the same as #3.

**Comment by DataTables** [comment]
NPM packages have been released for Buttons - see:

* [DataTables NPM documentation](http://datatables.net/download/npm)
* [Blog on the topic](http://datatables.net/blog/2015-11-09).
