### ISSUE TITLE
excelHtml5 Creates Corrupted XLSX File when ™ is in the Sheet Name

### ISSUE THREAD

**Issue by periapsistech** [DataTables/Buttons#183]
Simply add ™ to the sheet name property and it will corrupt the Excel file, removing it will resolve the issue.

**Comment by DataTables** [comment]
How interesting - thanks for reporting that. What happens if you use `&trade;` or `&#8482;`?

**Comment by periapsistech** [comment]
Ineed!
`&trade;` is handled as plain-text and causes the error
`&#8482;` is handled as plain-text and causes the error
`\u2122` works and is rendered properly
