### ISSUE TITLE
Excel export generates a corrupted file while accessing site via proxy/vpn.

### ISSUE THREAD

**Issue by on3ss** [DataTables/Buttons#185]
I have a site that's running in a closed network. When I download the excel file within that network it generates the excel file with no problem but when an employee outside the network wants to connect to the site they have to do so via the company's vpn/proxy. This is where the excel file generated is always corrupted. Also the filename is always some garbage values and not the one specified in the config.

Here's the code for reference:
```
$('#downloadefttbl').DataTable({
    dom: 'Bfrtip',
    buttons: [{
        extend: 'excelHtml5',
        text: 'Save EFT',
        messageTop: 'EFT',
        className: 'btn bg-info text-white',
        title: 'Treasury EFT',
        sheetName: 'Main Sheet'
    }]
});
```

**Comment by AllanJard** [comment]
I didn't reply to this at the time - sorry! Is this still an issue? Can you link to a test case showing the issue please.

**Comment by AllanJard** [comment]
Going to close for now. Need a test case to be able to reproduce this. If you have one, please reopen with a link to a repo showing the issue.
