### ISSUE TITLE
npm package: Bulma JS is missing

### ISSUE THREAD

**Issue by sommer-gei** [DataTables/Buttons#187]
Hi, today I tried DataTables (after [the great announcement in June](https://datatables.net/blog/2021-06-10#Bulma)) in a small PHP project by installing the npm packages with Composer (using https://asset-packagist.org; because I don't have any need to compile any assets by myself).

This is the current situation for the packages:
```shell
# composer info
composer/installers                   v1.11.0 A multi-framework Composer library installer
npm-asset/bulma                       0.9.3
npm-asset/datatables.net              1.10.25
npm-asset/datatables.net-bm           1.10.25
npm-asset/datatables.net-buttons      1.7.1
npm-asset/datatables.net-fixedheader  3.1.9
npm-asset/font-awesome                4.7.0
npm-asset/jquery                      3.6.0
oomphinc/composer-installers-extender 2.0.0   Extend the composer/installers plugin to accept any arbitrary package type.
phpmyadmin/sql-parser                 5.4.2   A validating SQL lexer and parser with a focus on MySQL dialect.
symfony/polyfill-mbstring             v1.23.1 Symfony polyfill for the Mbstring extension
```

As you can see, `datatables.net-buttons` is installed in version `1.7.1` (which is the [current release/tag](https://github.com/DataTables/Buttons/releases)) and Bulma is supportet since version [1.7.0](https://cdn.datatables.net/buttons/1.7.0/).

But now I'm missing the (new) files `buttons.bulma.js` and `buttons.bulma.min.js`. The folder of the npm package only has this files:
```shell
./datatables.net-buttons/
├── js
│   ├── buttons.colVis.js
│   ├── buttons.colVis.min.js
│   ├── buttons.flash.js
│   ├── buttons.flash.min.js
│   ├── buttons.html5.js
│   ├── buttons.html5.min.js
│   ├── buttons.print.js
│   ├── buttons.print.min.js
│   ├── dataTables.buttons.js
│   └── dataTables.buttons.min.js
├── License.txt
├── package.json
└── Readme.md
```

Beside this, there are some more folders and files missing if you take a look at the list of the [`1.7.1` release page](https://cdn.datatables.net/buttons/1.7.1/) …

**Can someone maybe help out, plz?** (I found the [`make.sh` script in this repo](https://github.com/DataTables/Buttons/blob/1.7.1/make.sh). May it be a/the solution to add the missing files there?)

Thanks a lot for your great work and KR!

**Comment by AllanJard** [comment]
You need to install `datatables.net-buttons-bm` to get the Bulma styling.

`datatables.net-buttons` is just the core package. Then you need a styling package (`-bm`, `-bs4` or whatever) to add the styling aspect.

**Comment by sommer-gei** [comment]
@AllanJard: Allen, you are the best! Thank you very much for the quick and working answer.

BR (+ sry for the _stupid_ answer ... ;-))!
