### ISSUE TITLE
schemas.openxmlformats.org no longer exists

### ISSUE THREAD

**Issue by lordterrin** [DataTables/Buttons#193]
buttons.js uses several schemas imported from `schemas.openxmlformats.org` - but this website appears to no longer exist.  When attempting to export .xlsx files, I now get an error on load that the file is corrupted.  I can fix it and remove the offending xml - but I am obviously trying to get around this for my users.

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to FILE.xml</logFileName><summary>Errors were detected in file '/Users/ASDF/Downloads/ASDF.xlsx'</summary><removedParts summary="Following is a list of removed parts:"><removedPart>Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Load error.</removedPart></removedParts></recoveryLog>`

I found what appears to be similar schemas hosted directly on microsoft at https://learn.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/6624db33-496c-47f7-a562-a54cb01b133f?redirectedfrom=MSDN

but these schemas all import from this same website.

**Comment by AllanJard** [comment]
[Have a look at this thread](https://www.docx4java.org/forums/pptx-java-f14/missing-host-for-schemas-openxmlformats-org-t378.html) which I think discusses the same issue.

As far as I am aware, the schemas Buttons uses are still correct. LibreOffice uses them, and [Wikipedia references it too](https://en.wikipedia.org/wiki/Office_Open_XML_file_formats).

**Comment by lordterrin** [comment]
Thank you Allan, (for literally everything, but for this too :) ) - I think you can close this issue.  After having read through the threat you posted, I believe my error is related to something ELSE.  I was attempting to access the URL, similar to the poster, and thought the error was related to this resource disappearing.

**Comment by AllanJard** [comment]
It really weirded me out as well when I tried it in my browser. Expect the unexpected 🙂
