### ISSUE TITLE
type is not a function

### ISSUE THREAD

**Issue by joao-saraiva** [DataTables/Buttons#198]
I tried to generate a new docker image for my project and after that i started to get an error m.type("select-checkbox",{className:"dt-select",detect:function(e){return"select-checkbox"===e&&e},order:{pre:function(e){return"X"===e?-1:0}}})

**Comment by AllanJard** [comment]
I strongly suspect you are using Buttons 3 with DataTables 1.x. Buttons 3 requires DataTables 2.0.0+.

**Comment by AllanJard** [comment]
Can you show me your package.json dependencies for datatables.net* please? There is an error in the dependency versions, but I would have expected DT2 to be pulled in with an old version of Buttons, not a new version of Buttons with an old version of DT!

If you can tell me how I can recreate the error, that would be really helpful.

**Comment by joao-saraiva** [comment]
Sorry for wasting your time, for some reason both libs in our project datatables.net-select and datatables.net-buttons were not with a fixed version and have caused some troubles.                                                                                                                                    we fixed putting datatables.net-select to 1.4.0 and datatables.net-buttons to 1.7.1

**Comment by AllanJard** [comment]
No problem. I'm going to have to go back to the old versions and issue patch releases, as some are currently saying they are compatible with DataTables 2 when they aren't... Good to hear you are back up and running though.
