### ISSUE TITLE
Buttons: too many iterations

### ISSUE THREAD

**Issue by cloudybrain** [DataTables/Buttons#2]
I been trying to follow this example:
https://editor.datatables.net/examples/advanced/localstorage.html

and after loading all my scripts, in my browser console I received the error:

Uncaught: Buttons: Too many iterations

I have no idea what this means, or what I'm doing wrong. But I can't follow this demo.

**Comment by DataTables** [comment]
Hi,

Could you link to the page so I can debug the issue please? As you can see in the example you link to it should work, so I'd need a link to the page showing the issue to be able to debug it.

**Comment by cloudybrain** [comment]
I have it on my dev computer, I can see if I can stand one up and port the code shortly. Right now I'm using tabletools, and that's working properly, and I'm in a bit of a hurry with my application.

**Comment by DataTables** [comment]
I know that feeling :-).

If you could put it up at some point that would be great. Thanks!

**Comment by cloudybrain** [comment]
Tried to replicate, and after updating datatables and buttons/select, it started to work.. I don't have this problem anymore!

**Comment by DataTables** [comment]
Sorry- I forgot to update this issue. I suspect it was resolved just a couple of days ago by 960e3e36506ecfdb5cb83e9df9c48d7895f3cb96.
