### ISSUE TITLE
Provide a filename option and allow it to be a function

### ISSUE THREAD

**Issue by DataTables** [DataTables/Buttons#20]
At the moment, the export files base the file name on the `title` parameter of the button configuration object. Really there should be a `filename` option so you can specify a title independently of the file name and it should be allowed to be a function so it can execute and return dynamic values.

**Comment by N4M3Z** [comment]
+1

**Comment by DataTables** [comment]
Forgot to close this issue when I committed the fix: f0e0254e2ee5a3f7c3b8246a99f6d3e16fb7e883.
