### ISSUE TITLE
Using a function for a column-selector in exportOptions/columns broken in 3.0.1

### ISSUE THREAD

**Issue by scoldwell** [DataTables/Buttons#201]
We are using a function in the columns property of exportOptions to filter out columns that weren't wanted for CSV export. This worked in version 2.4.2 but is not in 3.0.1.  The `node` parameter passed into the function is undefined for every iteration. It also appears as though the function is called multiple times for the same set of columns.

Here is a link showing the problem:  https://live.datatables.net/weyiduyo/1/edit

**Comment by scoldwell** [comment]
I was able to find a workaround using a css selector, but the bug should probably be fixed regardless.

https://live.datatables.net/layezobu/1/edit

**Comment by AllanJard** [comment]
Apologies for the delay in replying here! The error was in fact in DataTables core, and [I've just committed a fix](https://github.com/DataTables/DataTablesSrc/commit/2a5b9b9791b7711947ef823455e580c9c96f3816) to address it. It will be in DataTables 2.0.4.
