### ISSUE TITLE
HTML5 buttons not working with latest versions.

### ISSUE THREAD

**Issue by alpozgur** [DataTables/Buttons#207]
Hi;
I just started to try and use 2.1.3 version in angular.. Here are the package.json content for datatables
    "datatables.net": "^2.1.3",
    "datatables.net-buttons": "^3.1.1",
    "datatables.net-buttons-dt": "^3.1.1",
    "datatables.net-colreorder-dt": "^2.0.0",
    "datatables.net-dt": "^2.1.3",
    "datatables.net-plugins": "^2.0.8",
    "datatables.net-responsive": "^3.0.2",
    "datatables.net-responsive-dt": "^3.0.2",

and angular.json

            "styles": [
              "node_modules/bootstrap/scss/bootstrap.scss",
              "src/styles.scss",
....
              "node_modules/datatables.net-dt/css/dataTables.dataTables.min.css",
              "node_modules/datatables.net-buttons-dt/css/buttons.dataTables.min.css",
              "node_modules/datatables.net-colreorder-dt/css/colReorder.dataTables.min.css",
              "node_modules/datatables.net-responsive-dt/css/responsive.dataTables.min.css",
              "node_modules/datatables.net-select-dt/css/select.dataTables.min.css",
              "src/assets/scripts/resources/fixedColumns.dataTables.min.css",
              "src/assets/scripts/resources/fixedHeader.dataTables.min.css",
              "src/assets/scripts/resources/rowGroup.dataTables.min.css",
             ....
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/jszip/dist/jszip.js",
              "src/assets/scripts/resources/pdfmake.min.js",
              "src/assets/scripts/resources/vfs_fonts.js",
              "node_modules/datatables.net/js/dataTables.min.js",
              "node_modules/datatables.net-buttons/js/dataTables.buttons.min.js",
              "node_modules/datatables.net-buttons/js/buttons.colVis.min.js",
              "node_modules/datatables.net-buttons/js/buttons.html5.min.js",
              "node_modules/datatables.net-buttons/js/buttons.print.min.js",
              "node_modules/datatables.net-colreorder/js/dataTables.colReorder.min.js",
              "node_modules/datatables.net-responsive/js/dataTables.responsive.js",
              "node_modules/datatables.net-select/js/dataTables.select.min.js"
....
            ],
and in ts
import { Config } from 'datatables.net';
import 'datatables.net-responsive';
import 'datatables.net-buttons-dt';

while extending excelHTML5 pr pdfHTML5 buttons, messageBottom, title, filename properties not works. When i look your sources, i saw that you set them to get properties of copy button...
Can you correct them or we need to use excel and pdf buttons?

**Comment by AllanJard** [comment]
Please link to a git repo that has a minimal test case that demonstrates the issue, or use a service such as StackBltiz to create the minimal test case showing the problem. I'm not aware of a problem with the HTML5 buttons and `messageBottom` (etc) at this time.

**Comment by alpozgur** [comment]
I tried to create a test case at stackbitz without success :( :( 
My main problem is about types....
my package.json and angular.json as i shared above... 
When i try to extend a button, for-example
        buttons: [
          {
            extend: 'colVis',
            text: "<i class='glyphicon glyphicon-eye-open' style='line-height: 1'></i><span> Columns</span>",
            columns:'alper',
            name: 'columnVisibility',
          },......

it says 'columns' does not exist in the type 'ButtonConfig'
but it's at there i saw...

changed the import side as follows
import DataTable  from 'datatables.net-bs5';
import 'datatables.net-buttons-bs5';
import 'datatables.net-responsive-bs5';

but no success... (if i won't extend colvis or excelHtml5 everything works...

**Comment by AllanJard** [comment]
When you say you couldn't get it to work on StackBltiz, do you mean the error didn't happen, or you couldn't get the stack as a whole to run? Its difficult to debug something without being able to see the issue.

**Comment by alpozgur** [comment]
At StackBltiz angular-datatables is not working.. Sorry for delay.. Here is the detailed problem of mine...
mine **package.json** 
  
  **"datatables.net": "^2.1.4",
    "datatables.net-bs5": "^2.1.4",
    "datatables.net-buttons": "^3.1.1",
    "datatables.net-buttons-bs5": "^3.1.1",
    "datatables.net-buttons-dt": "^3.1.1",
    "datatables.net-colreorder": "^2.0.4",
    "datatables.net-colreorder-dt": "^2.0.4",
    "datatables.net-dt": "^2.1.4",
    "datatables.net-plugins": "^2.0.8",
    "datatables.net-responsive": "^3.0.2",
    "datatables.net-responsive-bs5": "^3.0.2",
    "datatables.net-responsive-dt": "^3.0.2",
    "datatables.net-select": "^2.0.5",
    "datatables.net-select-bs5": "^2.0.5",
    "datatables.net-select-dt": "^2.0.5",
    "jquery": "^3.7.0",
    "jszip": "^3.10.1",**
in **angular.json**
**"styles": [
              "node_modules/bootstrap/scss/bootstrap.scss",
              "src/styles.scss",
              "node_modules/datatables.net-dt/css/dataTables.dataTables.min.css",
              "node_modules/datatables.net-bs5/css/dataTables.bootstrap5.min.css",
              "node_modules/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css",
              "node_modules/datatables.net-colreorder-dt/css/colReorder.dataTables.min.css",
              "node_modules/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css",
              "node_modules/datatables.net-select-dt/css/select.dataTables.min.css",
              "node_modules/datatables.net-select-bs5/css/select.bootstrap5.min.css"
            ],
"scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/raphael/raphael.js",
              "node_modules/tether/dist/js/tether.min.js",
              "node_modules/datatables.net/js/dataTables.min.js",
              "node_modules/datatables.net-buttons/js/dataTables.buttons.min.js",
              "node_modules/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js",
              "node_modules/jszip/dist/jszip.js",
              "node_modules/pdfmake/build/pdfmake.js",
              "node_modules/pdfmake/build/vfs_fonts.js",
              "node_modules/datatables.net-buttons/js/buttons.html5.min.js",
              "node_modules/datatables.net-buttons/js/buttons.print.min.js",
              "node_modules/datatables.net-buttons/js/buttons.colVis.min.js",
              "node_modules/datatables.net-colreorder/js/dataTables.colReorder.min.js",
              "node_modules/datatables.net-responsive/js/dataTables.responsive.min.js",
              "node_modules/datatables.net-select/js/dataTables.select.min.js",
              "node_modules/datatables.net-select-bs5/js/select.bootstrap5.min.js"
            ],**
in my **component.ts

import { Config } from 'datatables.net-dt';
import 'datatables.net-responsive';
import 'datatables.net-bs5';
import 'datatables.net-buttons-dt';
import 'datatables.net-buttons-bs5';
@Component({
  selector: 'app-mycmp',
  templateUrl: './my.component.html',
  styleUrls: ['./my.component.scss'],
})
export class myComponent implements AfterViewInit{
@ViewChild(DataTableDirective, { static: false }) dtElement: DataTableDirective;
dtOptions: Config = {};
dtTrigger: Subject<Config> = new Subject<Config>();
  @ViewChild('dropdownTemplate', { static: true }) myTemplate!: TemplateRef<{ data: any }>;
  ngAfterViewInit(): void {
    setTimeout(() => {
    
      const self = this;
      this.dtOptions = {
        destroy: true,
        pagingType: 'numbers',
        pageLength: 10,
        lengthMenu: [[10, 25, 50, 100, -1], [10, 25, 50, 100, "Tümü"]],
        processing: false,
        responsive: true,
        scrollCollapse: true,
        drawCallback: function () {
          var dtLength = this.api().rows({ filter: 'applied' }).data().length;
          var hasRows = dtLength > 0;
          $('.btn-Ekle')[0].style.display = !self.helper.user_is_outworker ? 'inline' : 'none'
          $('.btn-CalismaEkle')[0].style.display = !self.helper.user_is_adayMuhendis && !self.helper.user_is_outworker ? 'inline' : 'none'
          $('.buttons-collection')[0].style.display = hasRows ? 'inline' : 'none'
          $('.btn-expandall')[0].style.display = hasRows && dtLength > 1 ? 'inline' : 'none'

          if (dtLength < 11) {
            $('.dt-length')[0].style.visibility = 'hidden'
          }
          else
            $('.dt-length')[0].style.visibility = 'visible'
        },
        columns:
          [
            {
              // Responsive control column
              data: null,
              defaultContent: '',
              className: 'control noVis',
              orderable: false
            },
           {
              title: 'Col 1',
              data: 'Col_1',
              visible: false,
              searchable: false,
              className: 'noVis'
            },
            {
              data: 'Col_N',
              visible: false,
              searchable: false,
              className: 'noVis'
            },
            {
              data: 'Col_1N',
              visible: false,
              searchable: false,
              className: 'noVis'
            },
            {
              title: 'Col_2',
              data: 'IZIN_ADI',
              responsivePriority: 2,
              className: 'all',
              visible: true
            }
          ],
        layout: {
          topStart: {
            buttons: [
              {
               extend: 'colvis',
              text: 'Sütunlar',
              columns: ':not(.noVis)',
              collectionLayout: 'fixed columns',
              postfixButtons: ['colvisRestore'],
               },              
              {
                text: '<i class= "feather icon-refresh-cw pr-1" ></i>',
                className: ' btn btn-outline-secondary btn-yenile',
                titleAttr: 'Yenile',
                action: function (e, dt, node, config) {
                  dt.ajax.reload();
                }
              },
              {
                text: '<i class= "far fa-calendar-plus pr-1" ></i> İslem Ekle',
                className: 'btn btn-outline-info',
                titleAttr: 'İslem Ekle',

                action: function (e, dt, node, config) {
                  self.openIslemModal();
                }
              },
              {
                text: '<i class= "far fa-calendar-alt pr-1" ></i>  OlayEkle',
                className: ' btn btn-outline-info',
                titleAttr: 'Olay Ekle',

                action: function (e, dt, node, config) {
                  self.openOlayModal();
                }
              },
              {
                extend: 'collection',
                text: '<i class= "feather icon-download pr-1" ></i> Dışa Aktar',
                className: ' btn btn-outline-warning',

                autoClose: true,
                buttons: [
                  {
                    text: '<i class= "feather icon-copy pr-1" ></i> Pano',
                    extend: 'copy',
                    className: 'btn btn-outline-success',
                    exportOptions: { columns: [5, 6, 7, 8, 9, 10, 11, 12, 13] }
                  },
                  {
                    extend: 'print',
                    text: '<i class= "feather icon-printer pr-1" ></i> Yazdır',
                    className: 'btn btn-outline-success',
                    exportOptions: { columns: [5, 6, 7, 8, 9, 10, 11, 12, 13] }

                  },
                  {
                    extend: 'excel', 
                    text: '<i class= "far fa-file-excel pr-1" ></i> Excel',
                    className: 'btn btn-outline-warning',
                    exportOptions: { columns: [5, 6, 7, 8, 9, 10, 11, 12, 13] }

                  },


                  {
                    extend: 'pdf',
                    text: '<i class= "far fa-file-pdf pr-1" ></i> PDF',
                    className: 'btn btn-outline-warning',
                    orientation: 'landscape',
                    exportOptions: {
                      modifier: {
                        pageSize: 'A4',
                        download: 'open'
                      },
                      columns: [5, 6, 7, 8, 9, 10, 11, 12, 13]
                    }
                  }
                ]
              },
          topEnd: ['pageLength', 'search'],
        },
        ajax: (dataTablesParameters: any, callback) => {
          if (self.searchForm.valid) {
            self.http.post(self.cns.baseUrl , {
              yil: self.selected_yil.value
            }).subscribe(resp => {
              callback({
                data: resp
              });
            });
          }
        },
      };
      this.dtTrigger.next(this.dtOptions);
    });
  
  }

}

**

when i try to extend colvis, typescript says 
_**Type '{ buttons: ({ extend: string; text: string; columns: string; collectionLayout: string; postfixButtons: string[]; } | { text: string; className: string; titleAttr: string; action: (e: any, dt: Api<any>, node: JQuery<...>, config: ButtonConfig) => void; } | { ...; })[]; }' is not assignable to type 'LayoutElement | LayoutFeatures'.
  Types of property 'buttons' are incompatible......
Object literal may only specify known properties, and 'columns' does not exist in type 'ButtonConfig'.ts(2322)
**_

**Comment by AllanJard** [comment]
I think I've fixed this with https://github.com/DataTables/Buttons/commit/c4db8db6b753f9747fad37226ea8ae3f5d20e1cf . 

To test, you could take [the contents of the type file](https://github.com/DataTables/Buttons/blob/master/types/types.d.ts) and paste it into your local `node_modules/datatables.net-buttons/types/types.d.ts`.

**Comment by alpozgur** [comment]
I copied, but the 		
collection: {
			extend?: 'collection',
			action?: FunctionButtonAction;
			align?: 'button-left' | 'button-right' | 'container' | 'dt-container';
			autoClose?: boolean;
			background?: boolean;
			backgroundClassName?: string;
			buttons: ButtonsList;
			className?: string;
			collectionLayout?: string;
			collectionTitle?: string;
			dropup?: boolean;
			fade?: number;
			popoverTitle?: string;
			postfixButtons?: ButtonsList;
			prefixButtons?: ButtonsList;
			span?: null | 'container' | 'dt-container';
		} | ButtonConfig;
section was missing. I added it and worked. And i noticed that 
copyHtml5: Buttons['copy'];
csvHtml5: Buttons['copy'];
excelHtml5: Buttons['copy'];
pdfHtml5: Buttons['copy'];
these makes html5 buttons not work as their original buttons... Are these correct or i misunderstood?

**Comment by AllanJard** [comment]
The collection button is now under `CollectionButtons`. That said, I did spot a few errors and [have committed another change](https://github.com/DataTables/Buttons/commit/8ac1bbb1069ef36fca3bdf3eb2561cff47d4c5a1). Perhaps you could try the latest version?

**Comment by AllanJard** [comment]
I'm not seeing that issue I'm afraid. I'm using TS 5.5.4. I'm not sure if that will make a difference.

**Comment by alpozgur** [comment]
I'm not sure then... But it worked as expected now.. Especially your commit about responsive :) :) solved my biggest problems :) Do you have any eta to publish new changes to npm? Cause all my teams will need these changes and i don't wanna share the code my mail... It had to be in node_modules and installed from npm...

**Comment by AllanJard** [comment]
I'll aim to get releases for Buttons and Responsive done by the end of the week.
