### ISSUE TITLE
Error in file generated for excel

### ISSUE THREAD

**Issue by Dillinjer** [DataTables/Buttons#21]
The excel file generated with excel button (both HTML5 and Flash) is corrupted if it has ~1500 or more rows. When I try to open the generated file in Excel 2013, it just shows a message saying that it found a problem with the file and asks if it can repair it. Clicking on repair doesn't solve the issue (not clicking either). I tried different datasets and still have same issue. From what I tested, it works fine if it has around 1200 rows or lower.
The layout is as following (7 columns):
[TextHeader][TextHeader][TextHeader][TextHeader][TextHeader][TextHeader][TextHeader]
[Text][Number][Date(dd/MM/yyyy)][Number][Number][Number][Text]

Thanks!

**Comment by DataTables** [comment]
Can you link to a page showing the issue please.

**Comment by Dillinjer** [comment]
Sorry but it is not a public application

**Comment by Dillinjer** [comment]
Here is the generated file:
https://drive.google.com/file/d/0B03jC3VnQkOhUklaLVhxZVpjTUE/view?usp=sharing

**Comment by Dillinjer** [comment]
@DataTables https://jsfiddle.net/51cuxtto/2/ 
here is an example of a table that doesnt work

**Comment by DataTables** [comment]
Hi,

Thanks for the links. It looks like this might be an issue with the Javascript / Flash bridge that your example was using. If [I use the HTML5 export button type](https://jsfiddle.net/51cuxtto/3/) it works okay. Your example wasn't using that as it wasn't including the JSZip files (so it was falling back to Flash).

As a workaround for the moment, perhaps don't include the Flash buttons in your application and use only the HTML5 export options?

**Comment by Dillinjer** [comment]
@DataTables Hm, seems that the example table that I generated doesn't have the issue because it also happens with HTML5 mode. My bad about the example, I forgot to put JSZip in it. I can't seem to replicate it with random data or look a like data, even with special characters. Maybe it is a hidden character that it is being populated with that is causing this issue but I can't seem to find it. I can't give you the exact data because it has client info inside, I did post earlier the file generated that is broken with some pvt data obfuscated.

**Comment by DataTables** [comment]
The key characters to check are `&`, `<` and `>` I think. Does your table include them?

I took a look at the file you linked to, but unzip says it isn't a valid zip file when I try to access its contents. 886K is that correct?

**Comment by Dillinjer** [comment]
Yes, that is correct. It is not zipped, you just open it with Excel. If you open in notepad you can see its unformated data.

**Comment by DataTables** [comment]
XLSX files are just zip files which contain a number of XML documents. If it isn't a valid zip file then Excel doesn't stand a hope and indeed my Mac version cannot repair that file.

**Comment by Dillinjer** [comment]
Hum, ok. Sounds like a problem when zipping then

**Comment by Dillinjer** [comment]
Just confirmed here, the problem is with hidden character, I ran a function to remove them and the file now open normally

**Comment by DataTables** [comment]
Ah - I've got a guess. I wonder if your browser is limiting the data url length that can be used. What browser and version are you using? Also, what happens in a different browser?

**Comment by DataTables** [comment]
Okay good. What hidden character?

**Comment by Dillinjer** [comment]
I don't actually know which one specifically. I run a function in .NET checks and removes all Control characters. It seems that it is this character: \u001f.
I tested in Chrome v45 and v46, Firefox 40, Microsoft Edge and IE11, all have some issue.

**Comment by Dillinjer** [comment]
I fixed the issue inserting xml = xml.replace(/[\u001f]/g, ""); in buttons.flash.js and buttons.html5.js after adding the footer. You think this could be made public so that other people don't have same issue?

**Comment by DataTables** [comment]
Yes - thanks for tracking that down. I'll test locally and commit the change in. I wonder why the zip is failing on that character... :-)

**Comment by Dillinjer** [comment]
Thanks for helping solving. I have another issue/suggestion. The way the copyHTML5 works isn't very good in my opinion. The default settings generate a text (that doesn't show correctly in my layout - it's almost completely hidden by other elements), and ask the user to hit ctrl+c. Why not just copy to clipboard when the user presses the button like in the Flash version? Look at Gerrit implementation (https://android-review.googlesource.com/#/c/170361/)

**Comment by DataTables** [comment]
> Why not just copy to clipboard when the user presses the button like in the Flash version?

Because there is no API to do that in HTML5 unless I'm missing it? Thanks for the link, but it looks like a single item change set: "Add system/tools/aidl to manifest". I'm not sure how that relates?

**Comment by Dillinjer** [comment]
@DataTables you misunderstood me, that link I gave was just an example of a working implementation of HTML5 Copy to clipboard, just click the black icons. Here is the api: http://www.w3.org/TR/clipboard-apis/ and example here http://www.htmlgoodies.com/html5/other/working-with-clipboard-apis-in-html5-web-apps.html

**Comment by DataTables** [comment]
Oh I see. The Gerrit implementation isn't easy to follow on initial inspection - this is the click event handler:

> function (){if(K5b()){return $6b(b,this,arguments)}else{var a=$6b(b,this,arguments);a!=null&&(a=a.val);return a}}

I'll need to dig into how that actually is implemented it looks interesting.

The spec you linked to notes:

> Synthetic events do not have default actions. In other words, while the script above will fire a paste event, the data will not actually be pasted into the document.

My understanding of that is equally that a copy event will fire a copy event, but not actually copy to clipboard.

If I try to execute the following the Chrome console it just gives an error:

```js
var copyEvent = new ClipboardEvent('copy', { dataType: 'text/plain', data: 'Data to be copied' } );
document.dispatchEvent(copyEvent);
```

A draft of that spec user to refer to a method of being able to write to the clipboard, but that appears to have been removed.

**Comment by Dillinjer** [comment]
@DataTables gerrit is opensource, maybe you could dig the source files and see how they did it

**Comment by DataTables** [comment]
Looking at the gerrit source [it uses `execCommand('copy')`](https://github.com/gerrit-review/gerrit/blob/eb10d12f41623749086c578efa8727f75e095bb0/gerrit-gwtexpui/src/main/java/com/google/gwtexpui/clippy/client/CopyableLabel.java#L279) to implement copy to clipboard without Flash, but also has a Flash fallback.

The detection of support for this command is [quite messy](https://github.com/gerrit-review/gerrit/blob/6d8d26a0ce4be20d3e4473a776505f29062fe30d/gerrit-gwtexpui/src/main/java/com/google/gwtexpui/user/client/UserAgent.java#L43).

However, that looks like a good option for improving the UI the Buttons presents in a future version.

**Comment by DataTables** [comment]
I've used a little bit of Javascript to remove the control characters now to ensure that the XML file created is valid.
