### ISSUE TITLE
CSS folder contains SCSS files

### ISSUE THREAD

**Issue by nebulousGirl** [DataTables/Buttons#25]
The CSS files are nowhere to be found in the repository which makes no sense when using bower.

**Comment by DataTables** [comment]
See #3. It is something I'm working on.

**Comment by d-werner** [comment]
+1

**Comment by DataTables** [comment]
Bower distribution packages have been released for Buttons - see:

* [DataTables Bower documentation](http://datatables.net/download/bower)
* [Blog on the topic](http://datatables.net/blog/2015-11-09).

**Comment by katkamrachana** [comment]
the `css` files are missing in latest  v1.4.2

**Comment by DataTables** [comment]
No - they aren't included in this repo. They are in the distribution repos - this is source code only.

**Comment by katkamrachana** [comment]
Okay. I did `bower install datatables-buttons#1.4.2`, but could not see the css files

**Comment by DataTables** [comment]
See the [DataTables bower documentation](https://datatables.net/download/bower), which I linked to above, for the packages to install.
