### ISSUE TITLE
bower: register package

### ISSUE THREAD

**Issue by limenet** [DataTables/Buttons#3]
Thanks for adding a `bower.json` file!

Unfortunately, I can't [find the package in the registry](http://bower.io/search/?q=datatables-buttons). Have you [registered it](http://bower.io/docs/creating-packages/#register)?

**Comment by DataTables** [comment]
Not yet. I will be soon :-)

**Comment by jeremysnyder** [comment]
+1 for this.

**Comment by plcart** [comment]
+1 for this

**Comment by yajra** [comment]
+1 thanks!

**Comment by jeremysnyder** [comment]
Is it possible for you to add the [Bower License](https://github.com/bower/bower.json-spec#license) to the `bower.json` file?  I am trying to create a [WebJar](http://www.webjars.org/) from the Bower package but they require the license to be set in the `bower.json` file.

**Comment by DataTables** [comment]
Yes, as noted above it is something I will be doing soon. Likely within the next 2 weeks.

**Comment by jeremysnyder** [comment]
Figured I would try and help you out, and submitted a pull request for you to review.  Hope it helps.

**Comment by N4M3Z** [comment]
+1

**Comment by xplicit** [comment]
When will the bower packages be available?

**Comment by DataTables** [comment]
Next week. I'll post back here when they are. I just need to wrap some other changes up. Probably available at the end of the week.

**Comment by limenet** [comment]
According to the registry, the package is now available. Correct, @DataTables ?

**Comment by DataTables** [comment]
Sort of :-). This is the source repo so it contains only source files such as SCSS files, etc. I'm going to be publishing distribution repos soon which will contain the "compiled" files.

**Comment by limenet** [comment]
Okay, I see! Thanks for all your work, looking forward to the distribution repos :)

**Comment by immortalcy** [comment]
@DataTables sorry for bugging here again but is the distribution repo ready?

**Comment by xplicit** [comment]
@immortalcy I've found and use these dist packages:
 
datatables.net-buttons   (scripts)
datatables.net-buttons-bs  (styles for bootstrap)
datatables.net-buttons-dt  (styles for datatables)

`bower search datatables.net-buttons`

**Comment by DataTables** [comment]
Yes - see [this blog post](http://datatables.net/blog/2015-11-09) on the DataTables site.

I've still to go through the various packaging bugs, such as this and add update comments, but yes, this is now resolved with the new packages.
