### ISSUE TITLE
some? UTF8 Characters don't export to csv properly

### ISSUE THREAD

**Issue by joe-meyer** [DataTables/Buttons#31]
I haven't dug into the cause of this or perhaps I need to be formatting my data a different way in my json encoding? Either way here's an example:

http://jsfiddle.net/50x1m4bt/2/

Note that the `Ñ` character ends up being `Ã‘` in the csv (HTML5 version)

**Comment by DataTables** [comment]
Have a look at #30. Let us know if it works for you.

**Comment by joe-meyer** [comment]
Ya it does resolve my issue, I stumbled across that PR just after I searched the open issues (silly default github filters). If you want to close this go ahead, or leave it open so others don't open up the same issue until something gets merged to fix it.

**Comment by DataTables** [comment]
Merging to #30.

Thanks for the feedback.
