### ISSUE TITLE
Export buttons error

### ISSUE THREAD

**Issue by bytestream** [DataTables/Buttons#32]
When trying to use the CSV export button I'm getting an error on numeric data:
````a[i].replace is not a function [buttons.html5.js - line 311]````

This is the data in my table:
````
Department	Count
Support	        2
````

I resolved the error by adding ````.toString()```` before the replace:
```javascript
s += boundary ?
	     boundary + a[i].toString().replace( boundary, '\\'+boundary ) + boundary :
	     a[i];
````

Similar export code exists in buttons.flash.js

I hope this helps.

**Comment by DataTables** [comment]
Have you tried the version of the file in this repo? I think this should already be fixed. If not, please link to a test case showing the issue.

**Comment by bytestream** [comment]
Ah you're right. This has been fixed in the master.

I was using ~1.0.3 provided by bower. Updating bower to master resolved it.

**Comment by wagedomain** [comment]
Any word on when this fix will be released? I don't want to push nightly code to production.

**Comment by DataTables** [comment]
Probably next week

**Comment by wagedomain** [comment]
For anyone else with this issue, it affects both versions 1.0.2 and 1.0.3. It seems safe to rollback to 1.0.1, though.
