### ISSUE TITLE
clicking CSV button gets Uncaught TypeError: a[i].replace is not a function

### ISSUE THREAD

**Issue by hawkeye64** [DataTables/Buttons#37]
<pre>
join								@	buttons.html5.js:311
_exportData						@	buttons.html5.js:323
DataTable.ext.buttons.csvHtml5.action	@	buttons.html5.js:482
(anonymous function)				@	dataTables.buttons.js:545
jQuery.event.dispatch				@	jquery-2.1.4.js:4435
jQuery.event.add.elemData.handle		@	jquery-2.1.4.js:4121
</pre>
This is the code in question:
<pre>
s += boundary ?
				boundary + a[i].replace( boundary, '\\'+boundary ) + boundary :
				a[i];
</pre>

**Comment by DataTables** [comment]
Can you link to a test case showing the issue please. Please also check, if you haven't, that this error exists with the development code that is available in this repo rather than just the current release.

**Comment by hawkeye64** [comment]
Hope this helps.

https://jsfiddle.net/642546ff/1/

**Comment by hawkeye64** [comment]
Clicking the CSV button does nothing. If you are using Chrome you can see the error in the Console window.

**Comment by DataTables** [comment]
Hi,

Using the [nightly version](http://datatables.net/download/nightly#Buttons) (i.e. from this repo) your example appears to work well: https://jsfiddle.net/642546ff/2/ .

**Comment by bankim** [comment]
Hi,
I am also facing same problem. For me, for one page of my project csv export is working fine but for other page it is not working. I am using the same code. After saw the nightly version comments above  I have modified the code but no luck. The error i am getting is below. I am using this functionality for meteor framework.
"Uncaught TypeError: a[i].replace is not a function"

If anyone can help me out for this problem it is really thankful.

**Comment by DataTables** [comment]
Please link to the page showing the problem so it can be debugged.

**Comment by bankim** [comment]
sorry.. my project is not in live url. can you please give me some idea how to resolved that issue.

**Comment by DataTables** [comment]
Not without a test case as I would need to debug the issue if you are using the current nicely.

**Comment by bankim** [comment]
But the same code is working fine for other page.

**Comment by DataTables** [comment]
And that is why I would need a link to the page showing the issue. I have absolutely no idea why it isn't working I'm afraid.

**Comment by bankim** [comment]
once i will deploy the code let u know.

**Comment by hawkeye64** [comment]
bankim, typically you reproduce the error on https://jsfiddle.net so it can be evaluated.

**Comment by michaelaaronle** [comment]
Passing into the data table json objects that contain things other than strings (int, float, etc) will cause this.

**Comment by DataTables** [comment]
@michaelaaronle - have you tried using the [nightly versions of the Buttons files](http://datatables.net/download/nightly#Buttons)? This issue should already be fixed. If you are using the nightly files and you are still seeing this issue, please link to a test case.

**Comment by manukeerampanal** [comment]
The reason for the issue is the function replace in the for loop. The issue occurs when a field in your table just contains numbers only. The replace function doesn't work with number since it is string function. The nightly version has the fix. If someone can't use nightly version, you can make it work by adding just a space or similar special character in the table filed which contains number only.

**Comment by anupam-dosar** [comment]
> Passing into the data table json objects that contain things other than strings (int, float, etc) will cause this.

This is exactly what was causing `Uncaught TypeError: a[i].replace is not a function` error.

As soon as I fixed that, I was able to export CSV without any issues.

Thanks a ton!

**Comment by AllanJard** [comment]
Can you give a link to a test case showing the issue with the latest version of Buttons please?

**Comment by anupam-dosar** [comment]
> Can you give a link to a test case showing the issue with the latest version of Buttons please?

Well I didn't have the luxury of using the latest version, the app I'm working on is using the older version and fixing JSON object with all string elements fixed the issue right away.

**Comment by rexshijaku** [comment]
I had a matrix of integers, converted all values  to strings just before setting them to Datatable and this error stopped showing up. Not a perfect solution, but it works.

**Comment by AllanJard** [comment]
Perhaps you can link to a test case showing that issues please?
