### ISSUE TITLE
Spell Mismatch

### ISSUE THREAD

**Issue by gauravmak** [DataTables/Buttons#4]
Sorry, I couldn't find the respective page to make an update and PR.

On this page - *http://datatables.net/extensions/buttons/config*, Under **Built in options** category, Line as follows : 
``The Buttons library provides a number of core options that at common to all button types.``
Should be
``The Buttons library provides a number of core options that are common to all button types.``

**Comment by DataTables** [comment]
Thanks! I've committed the change locally and will push it out shortly. Only the reference material is included in the public repos which is why you wouldn't find this one.
