### ISSUE TITLE
Cannot declare buttons in DataTable Defaults.

### ISSUE THREAD

**Issue by michaeldjeffrey** [DataTables/Buttons#40]
It seems that if you want buttons on a table, you must pass them in the options at initialization time.

http://jsbin.com/pazepi/edit?js,output

**Comment by DataTables** [comment]
Thanks for noting this. Here is an update of your example using the nightly version of Buttons: http://jsbin.com/mexadepada/edit?html,js,output .

**Comment by michaeldjeffrey** [comment]
Awesome, thank you very much :smile:
