### ISSUE TITLE
Use clipboard.js to copy to clipboard

### ISSUE THREAD

**Issue by Misiu** [DataTables/Buttons#41]
I just found https://github.com/zenorocha/clipboard.js
It allows to copy to clipboard using execCommand and has a fallback that use select.
Maybe this could be used to allow copying?
ng-clip (https://github.com/asafdav/ng-clip/tree/clipboard-js) is already using this.

**Comment by DataTables** [comment]
Agreed. I've already got this bookmarked to look into it and find some time to integrate it into Buttons.

**Comment by zenorocha** [comment]
+1 ;)
