### ISSUE TITLE
Separate title & filename param values not working

### ISSUE THREAD

**Issue by pderksen** [DataTables/Buttons#42]
When I set both the `title` and `filename` params, in that order, and separate values, it seems the title also takes on the filename param.

Tried with the bleeding edge copies of `dataTables.buttons.js`, `buttons.bootstrap.js` & `buttons.html5.js`

Possibly related to https://github.com/DataTables/Buttons/issues/20

Thanks in advance!

**Comment by DataTables** [comment]
Can you link to the page please?

**Comment by pderksen** [comment]
@DataTables It was residing locally, so I simplified it into a test project for you.

https://dl.dropboxusercontent.com/u/7727/nexus/datatables-buttons-test.html

Thanks for taking a look.

**Comment by DataTables** [comment]
Awesome - thanks! Nightly packages are rebuilding with the fix now.

**Comment by pderksen** [comment]
Works perfect. Thank you!
