### ISSUE TITLE
Allow for Pre and Post Actions.

### ISSUE THREAD

**Issue by michaeldjeffrey** [DataTables/Buttons#46]
I can't find a good way to do things before or after a buttons action has occurred. 

Here's what I ended up doing. 

I went in to https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js#L561 and added 
```javascript
 
if ( ! button.hasClass( buttonDom.disabled ) && config.preAction ){
    config.preAction.call( dt.button( button ), e, dt, button, config );
}
```

I would have done the same thing for `postAction` but that wouldn't support async actions.

https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js#L819 I added
```javascript

if(conf.postAction){
    var _originalAction = conf.action;
    conf.action = function(e, dt, button, config){
        _originalAction.call(this, e, dt, button, config);
        conf.postAction.call(this, e, dt, button, config);
    }
}
```

That groups the execution of the postAction more tightly to the true finish of the button's Action.

These inclusions changed the way I had to do my lazy require I mentioned in https://github.com/DataTables/Buttons/issues/43.

Instead of being able to go straight to the html5 action I wanted and wrapping it in an async, I had to it after it had been attached to the buttons config, or it would do the same thing as if I'd put it inline with the `preAction` call. 

So I had to commit a sin. 
```javascript
var _OriginalBuildButton = $.fn.dataTable.Buttons.prototype._buildButton;

$.fn.dataTable.Buttons.prototype._buildButton = function(conf, collectionButton){
    if(conf.name && conf.name === 'excel'){
        var originalAction = conf.action;
        conf.action = function(...args){
            require.ensure(['jszip'], function _excelHtml5Action(){
                // Exports the JSZip object. Up to us to strap it to the window.
                window.JSZip = require('jszip');
                originalAction(...args);
            }, 'datatable_exports_lazy')
        }
    }
    return _OriginalBuildButton.call(this, conf, collectionButton);
};
```

I added a `name` attr to all my actions for identification purposes.

If you have anything in mind for a better way to handle all this nonsense. Please

**Comment by DataTables** [comment]
That's interesting - thanks. I haven't put this into Buttons already as I'm concerned as to what would happen if you need to have a `pre` or `post` action on that button that already has a `pre` or `post` action! That would then require a `prePre` / `postPost` action - gulp...

My inclination is currently to have the extended button define its own action and have that call the action function of the button that it wants to extend - a bit like calling `super()` in an OO language, but a bit more verbose.

**Comment by michaeldjeffrey** [comment]
I think if there were some `pre/post` events thrown around the execution of the action (Akin to Bootstraps events for modals, tooltips and the likes) that might help. The reason I didn't go with that solution is because you don't seem to have many events in the library already, and I didn't want to propose a code solution that is of a completely different style than what we're working with.

I can get behind the idea of making the extended buttons action explicitly call the action. I'm not sure of the best way to get at the actions from inside an action so it still goes through the `_resolveExtends`.

With the `super()` way, people who are trying to lazily load an action will still get a race condition where the `postAction` get called immediately after the `action` even though the action hasn't actually completed.

**Comment by DataTables** [comment]
The problem with `pre/post` events is that an async action such as loading an external script would not be complete before the action function itself is then executed. These events might be useful in some cases - when synchronous actions are all that are required, but I'm not sure they would help in this case.

**Comment by michaeldjeffrey** [comment]
ahh, true. I think this would work with Promises, but that's a lot of work for one case. :/

**Comment by DataTables** [comment]
You can now do post actions on a button with the `buttons-action` event - 696e16154ac08afe39a1faf7c54ab11e7e30894c. I think that's probably as far as I want to take it at the moment. I'm not sure how useful a pre event would be, but will consider it in future if there is a solid use case for it. For now going to close.
