### ISSUE TITLE
Problem with tfoot and thead in excel file

### ISSUE THREAD

**Issue by Dillinjer** [DataTables/Buttons#47]
Hi,

 I found one more issue with the generated excel file. When thead has multiple lines, it will only show the last one in the excel file, and tfoot content doesn't show at all.

Thanks!

**Comment by DataTables** [comment]
Hi,

It is correct that only a single header row will be exported in the created files - the cells which have been detected as the unique cells for that column will be used. Multi-row head export is not currently supported.

Regarding the footer  that should work (although again not multi-row). Can you link to a test case showing the issue please.

**Comment by Dillinjer** [comment]
Hi,

  Here is an example of tfoot not exporting to excel:

https://jsfiddle.net/o9y9a2jk/1/

**Comment by DataTables** [comment]
Thanks for the link. The footer is not included by default - http://datatables.net/reference/button/excel . If you want it to be included you just need to add `footer: true`: https://jsfiddle.net/o9y9a2jk/2/ .

I'm not sure why I made that the default - seems a bit odd, but there it is...

**Comment by Dillinjer** [comment]
Ah ok, thanks! Weird for it not being default....
