### ISSUE TITLE
Title for buttons

### ISSUE THREAD

**Issue by disovi** [DataTables/Buttons#48]
It would be nice to have an option for setting attribute title for button. For example when using iconic buttons.

**Comment by DataTables** [comment]
Good idea - thanks.

**Comment by DataTables** [comment]
Fixed here: 24dba19c1d021625fa3ab84f59a95de35bb40788 . Will be in the next release!

**Comment by disovi** [comment]
thanks! I think pdfHtml5 button needs some fix, because it uses title option too.

**Comment by DataTables** [comment]
Bother - yes it does. I'll need to rename this option. Thanks for pointing that out.
