### ISSUE TITLE
Unavailable buttons still show up when using extend

### ISSUE THREAD

**Issue by michaeldjeffrey** [DataTables/Buttons#49]
If you declare a button by saying you want to extend it, and it turns out you can't use that button. It still get's put inline with no text.

http://jsbin.com/reyufosazo/edit?js,output

I think it comes from https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js#L771
It fails to resolve a button it can't use, so returns false. But nothing is there to stop a false from continuing.

**Comment by DataTables** [comment]
Thanks - I'll get the fix for this committed in tomorrow. Brilliant test case!
