### ISSUE TITLE
When can we expect Buttons 1.1.0?

### ISSUE THREAD

**Issue by Tklaversma** [DataTables/Buttons#51]
Since the current dev-branch 1.1.0 of Buttons [supports](https://www.datatables.net/forums/discussion/31030/editing-cells-just-before-exporting-to-excel-pdf) ```format``` in the ```exportOptions```, I would like to know when we can expect the release of Buttons 1.1.0? Or better yet, can we expect dev-builds options in the Download builder any time soon? 

Regards,
TK

**Comment by DataTables** [comment]
> Or better yet, can we expect dev-builds options in the Download builder any time soon?

No - I have no plans to add dev builds to the download builder because of the amount of disk space and / or (its a trade off) processor utilisation it would place on the server.

I plan for 1.1.0 to be release later this week - assuming all goes well.
