### ISSUE TITLE
Modifying cell data before export

### ISSUE THREAD

**Issue by majksner** [DataTables/Buttons#52]
I couldn't find example how to modify cell data before exporting to pdf or csv. In tablestools this was possible with `fnCellRender`. Is there something similar in Buttons?

**Comment by DataTables** [comment]
See: 

* [Example for current release](https://github.com/DataTables/Buttons/blob/master/examples/html5/outputFormat-orthogonal.xml)
* [Example for up coming 1.1.0 release](https://github.com/DataTables/Buttons/blob/master/examples/html5/outputFormat-function.xml).

Both examples will be available on the site when I make the next release - soon.
