### ISSUE TITLE
Add friendly warning when dom: 'B' provided, but no button config

### ISSUE THREAD

**Issue by cdaringe** [DataTables/Buttons#53]
We run all of our tables through the same table initializer function.  I had set `dom: 'B...'` as default, but in some cases, I added the buttons after initialization.  Because `B` was set, but no config was present and [this is undefined](https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js#L57).  It is called because the dom attr finds "B", i.e.:

```js
// DataTables `dom` feature option
DataTable.ext.feature.push( {
	fnInit: function( settings ) {
		var api = new DataTable.Api( settings );
		var opts = api.init().buttons;

		return new Buttons( api, opts ).container();
	},
	cFeature: "B"
} );
```

This is **not a datatables bug**, but I thought it may be worth considering in the code snippet above to add a `if ( !opts ) throw new ReferenceError('table initialized with Buttons pane location, but no buttons config')`, or similar!

Just throwin' out ideas!  Thanks,

Chris

**Comment by DataTables** [comment]
Thanks for pointing this out. Let me have a little think about this one. Generally speaking I don't include such usage error catches in the software for worry about code bloat - however, the software done carry some general purpose errors for common issues.

I'm going to leave this one open to see if it is a common error, and is so, I'll add it in.

**Comment by DataTables** [comment]
I've had a bit of a think about this, and while I see the point about adding an error catch, I think there is also a use case for not including the `buttons` option, but including the `B` in `dom` - which is to use the defaults that have been set for Buttons.

As such, I'm going to close this issue - but I will keep an eye out for similar issues and if it does become a well known issue I will look at making the `buttons` option mandatory.
