### ISSUE TITLE
Column toggle menu doesn't go away on tablets.

### ISSUE THREAD

**Issue by trigun539** [DataTables/Buttons#57]
Testing the colvis part of datatable buttons on tablet, but the menu doesn't go away.

**Comment by DataTables** [comment]
Please link to a test case showing the issue using Buttons 1.1.0 (the current release).

**Comment by DataTables** [comment]
I've just tried this on an iPad with iOS 9.2 and it appears to work as expected.

Until a test case can be provided showing the issue, I'm going to close this ticket.
