### ISSUE TITLE
Can't use colvis button when installed through npm

### ISSUE THREAD

**Issue by lsapan** [DataTables/Buttons#58]
After installing `datatables-buttons` from npm, it seems to load properly, but throws this error when trying to use the `colvis` button: `Cannot extend unknown button type: colvis`

I've tried looking around for other npm packages like datatables-buttons-colvis, but I haven't been able to find any. Is there a way to use the column visibility plugin with the buttons npm package?

**Comment by DataTables** [comment]
Have you tried including the required Button definition file?

```js
require( 'datatables.net-buttons/js/buttons.colVis.js' );
```

See also [this thread in the DataTables forums](https://datatables.net/forums/discussion/31521/can-t-use-colvis-from-datatables-buttons-npm-package).
