### ISSUE TITLE
table.button('selector') are not consistent?

### ISSUE THREAD

**Issue by particlememory** [DataTables/Buttons#59]
Hi,

I would like to know how to achieve similar example at here: https://jsfiddle.net/gr5er1pj/2/
There is two a href button to link to particular button via table.button API

I try to modify the example and come up with this: https://jsfiddle.net/wt45q92h/1/
But the Export CSV are not working on my modification. 

However, i see not reason it will not work.

Thanks.

**Comment by DataTables** [comment]
There is an error in the version of Buttons you are using (v1.0.3) which is causing a Javascript error when exporting the data to CSV. If you update to the latest release of Buttons (1.1.0) this should be resolved.
