### ISSUE TITLE
Support Complex Header Automatically?

### ISSUE THREAD

**Issue by edwardchanjw** [DataTables/Buttons#60]
Does the **Buttons** support Complex Header as https://datatables.net/examples/advanced_init/complex_header.html

Thanks.

**Comment by DataTables** [comment]
Do you mean on file export? If so, then no. Colspan and rowspan can't really be represented in CSV or TSV.

**Comment by donnykurnia** [comment]
@DataTables how about print it or export it to xls? How can I help to get this implemented?

**Comment by DataTables** [comment]
It isn't something I'm planning to implement myself in the near future. Before I do so I want to improve DataTables' own complex header abilities, including API methods to get the header for extensions such as this to use.

As a workaround you could read the `thead` element straight from the document and modify the print / xlsx export to use that read data.
