### ISSUE TITLE
null TypeError when printing table footer

### ISSUE THREAD

**Issue by chipco** [DataTables/Buttons#64]
I have a general table init options object. For the print button I use `footer: true`. Some tables have a total footer, some do not have any footer. When I click the print button for a table that does not have a footer the js crashes with `TypeError: a is null`.

**Comment by DataTables** [comment]
Can you link to a test case showing the issue so it can be debugged please.

**Comment by DataTables** [comment]
Oops - pressed the wrong button! Reopened for test case to be provided.

**Comment by chipco** [comment]
https://jsfiddle.net/29z5qpj4/1/

I fixed my code checking if footer exists `$('table.data-table tfoot').length > 0` for now.
