### ISSUE TITLE
add support for colspan in tfoot when exporting

### ISSUE THREAD

**Issue by chipco** [DataTables/Buttons#66]
At the moment any colspan in the table footer is replaced by several single cells, repeating the content of the multi-cell, which is not desirable. The exported table should maintain the structure of the original table.

Test case: https://jsfiddle.net/Lr77dgmt/3/

**Comment by DataTables** [comment]
Looks like a duplicate of #63.

**Comment by chipco** [comment]
sorry, forgot I posted that issue already
