### ISSUE TITLE
Excel export sometimes corrupt

### ISSUE THREAD

**Issue by msvendsen** [DataTables/Buttons#68]
Hey!

I'm having some funny issues with Button's Excel export. Sometimes Excel-file is corrupt - sometimes it works fine.
In both cases I can extract the files as zip - this it's not the the zipping that is the issue (I use latest JSZip v2.5.0-15).
I'm Ussing latest Buttons version 1.1.0.

First I thought the issue was because of special non-English characters - but both files are with non-English characters... Maybe issue is size/length/#row related or some encoding?

This file is corrupt:
https://www.dropbox.com/s/v7qw8xja6zslxx8/test-corrupt.xlsx

This file works fine:
https://www.dropbox.com/s/gmbc7i0u9vi3isv/test-works.xlsx

Both files are extractable - so maybe you can see more details about where exactly the issue is.

**Comment by DataTables** [comment]
Can you try using the version from this repo please. It contains a number of fixes that are not present in the current release.

**Comment by msvendsen** [comment]
Just tried - same issue.. :(

**Comment by DataTables** [comment]
Thanks. I'll try to take a look this week or next. If you could provide a link to a test page showing the issue (although the generated files from before will be useful) that would be great.

**Comment by DataTables** [comment]
Thanks for the files. Its looks like the issue was coming from the dates ("05.01.2016" for example) which were incorrectly being written as numbers to the Excel file, which Excel was rightly rejecting. The above fix addresses that issue.

**Comment by msvendsen** [comment]
Super!
Confirmed working!
Thanks for super fast response and solution!
