### ISSUE TITLE
Excel: Support shared strings and formatting options

### ISSUE THREAD

**Issue by DataTables** [DataTables/Buttons#71]
Just as the title stays.

**Comment by vol7ron** [comment]
What do you mean by *shared strings*?

**Comment by DataTables** [comment]
Its part of the Excel standard. At the moment the file Buttons creates uses inline strings. I want it to used shared strings, in future.

**Comment by vol7ron** [comment]
Ahh.  I found this blog article interesting: http://openxmldeveloper.org/blog/b/openxmldeveloper/archive/2013/12/16/advice-when-generating-spreadsheets-use-inline-strings-not-shared-strings.aspx

I'm sure you've already considered it, but might be worth consideration.  Admittedly, I only glanced at the Buttons Excel and haven't looked into it too deeply beyond that.

**Comment by DataTables** [comment]
Going to close this now. With the release of Buttons 1.2 we rewrote how the Excel export works. It doesn't need to use shared strings - I had incorrectly thought that was required for formatters, but that isn't the case. We can use formatters with inline strings, which 1.2 now allows.

**Comment by Furgas** [comment]
Sorry for digging it up. I came here from [New lines are not being exported to Excel](https://datatables.net/forums/discussion/32470/new-lines-are-not-being-exported-to-excel) post. This issue is closed, but I still can't export new lines to Excel. How should I proceed? Or is it a lost cause?

**Comment by DataTables** [comment]
You need to do two things:

1. Disable the newline removal in the export options for the button
2. Enable wrapping in the cell - done by using style 55 ([full list of built in styles](https://datatables.net/reference/button/excelHtml5#Built-in-styles). [This example](https://datatables.net/extensions/buttons/examples/html5/excelTextBold.html) shows how you can set a style.
