### ISSUE TITLE
Inappropriate Mouse Cursor with Buttons and Bootstrap Style

### ISSUE THREAD

**Issue by yihui** [DataTables/Buttons#76]
Originally reported at https://github.com/rstudio/DT/issues/252

I looked at the example at http://datatables.net/extensions/buttons/examples/styling/bootstrap.html, and the problem does not exist there because of `a {cursor: pointer}` defined in site-examples.css. I guess it makes more sense to define it in buttons.bootstrap.css.

**Comment by DataTables** [comment]
Bootstrap's CSS has:

```css
.btn {
    ...
    cursor: pointer;
    ...
}
```

That is defined in `buttons.less` line 13.

**Comment by yihui** [comment]
But colvis buttons do not seem to be using `.btn` at all:

<img width="1271" alt="screen shot 2016-03-22 at 4 04 24 pm" src="https://cloud.githubusercontent.com/assets/163582/13967979/04ff8376-f048-11e5-9aff-4ecf6c5d29c6.png">

**Comment by DataTables** [comment]
Thanks for the clarification. The `btn` class isn't needed there ([Bootstrap docs](http://getbootstrap.com/components/#btn-dropdowns)), but its markdown is slightly different in that it has an `href` tag. I've added that now and it resolves the issue.

The nightly is up to date (although the DataTables site uses the current release version, so the issue will still be visible there).

**Comment by yihui** [comment]
Great. Thanks!

**Comment by yihui** [comment]
Actually the issue was not really fixed. It seems the patch was only applied to the top-level buttons but not the buttons in the dropdown menu.

**Comment by DataTables** [comment]
Thanks - fixed properly now! I forgot to disable the class I was using on the `a` before...

**Comment by yihui** [comment]
Okay, I can confirm it is indeed fixed this time. Thanks!
