### ISSUE TITLE
Buttons Only Work Once if at all in Chrome

### ISSUE THREAD

**Issue by flipper44** [DataTables/Buttons#78]
Buttons Seldom Work, or work only once for PDF and Excel.
Get a download option, but upon download I get a Failed - No File Message
![image](https://cloud.githubusercontent.com/assets/16003063/14045427/2bdbaa66-f268-11e5-942b-7b6afe2ceb9b.png)
You can see this action on:
https://datatables.net/extensions/buttons/examples/html5/simple.html 

Granted this is a Chrome beta Version 50.0.2661.49 beta-m (64-bit) screenshot, but I am having the same Problem on Chrome for android

**Comment by DataTables** [comment]
Seems to work no problem for me on Chrome 49.0.2623.87 Mac.

If there are no errors or warnings shown int he console it would be worth reporting to the Chrome bug tracker.

**Comment by flipper44** [comment]
Actually I just realized I am on Chrome Beta on Android as Well, so this seems to be something on the Beta channel

**Comment by DataTables** [comment]
If you log an issue with Chrome, could you link to it here as well please? Thanks!

**Comment by flipper44** [comment]
I logged it through the browser Report function and No clue where it goes
from there

On Fri, Mar 25, 2016 at 9:59 AM, Allan Jardine <notifications@github.com>
wrote:

> If you log an issue with Chrome, could you link to it here as well please?
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DataTables/Buttons/issues/78#issuecomment-201322472>
>



-- 


*Scott Hameister | www.mpowerinnovations.com
<http://www.mpowerinnovations.com/>________________________________________**mPower
Innovations*
1051 N Lynndale Drive, Suite 2A, Appleton, WI 54914
Main: (877) 269-6971 x 204 <%28877%29%20269-6971%20x%20207> | Mobile: (920)
419-6250 <%28920%29%20470-0292>

**Comment by DataTables** [comment]
Going to close for now. If you see this in Chrome stable or ever happen to hear back from the Chrome team, any updates would be very welcome.
