### ISSUE TITLE
Select button with `init` function doesn't enable and disable

### ISSUE THREAD

**Issue by dbalders** [DataTables/Buttons#79]
If you have a button that is a select button (`extend: 'selected'`) and you add an init function onto that button, it no longer follows the selected functionality. It will load as enabled, and wont toggle between enabled and disabled when rows are selected.

Example code: http://live.datatables.net/nakanavi/1/

![buttons init select](https://cloud.githubusercontent.com/assets/4715098/14252289/78b91a64-fa3b-11e5-9d52-d9a80d752147.gif)

OS: Mac OS X 10.11
Browser: Chrome 49.0.2623.87

**Comment by DataTables** [comment]
Hi,

This is actually expected as the [default `init` function is what will use the `enable` and `disable` methods](https://github.com/DataTables/Select/blob/master/js/dataTables.select.js#L981) to change the button's state.

Suppling your own `init` method will overwrite the default and thus result in the issue you are seeing.

I've wondered before about having some kind of `super()` method that will call the host button's own init...

**Comment by dbalders** [comment]
Ah, I see. That makes sense. I am using the init to check to see if a button should be removed or not based on the data from the server. Knowing that it is just overwriting the init for the select function, I wonder if i could use preInit or maybe even xhr to check to see if it needs to be removed and then leave the init to do its thing. That might actually work better functionality wise too to prevent any chance of the button showing up for a millisecond waiting for init to fire.

**Comment by DataTables** [comment]
So the way to do this, at least for now, is you call the `init` method of the original button:

            init: function ( dt, node, config ) {
                // Do custom processing
                // ...
 
                // Call the default `select` action method
                $.fn.dataTable.ext.buttons.select.init.call(this, dt, node, config);
            }

Its a fairly long function name (nested), but that will do the job nicely. I can't really think of a better way to expose some kind of `super` method.

**Comment by exodus4d** [comment]
Thanks, would be nice to add this to the docs ;)
