### ISSUE TITLE
inline dependancies

### ISSUE THREAD

**Issue by MuellerMatthew** [DataTables/Buttons#80]
Allan,
How often do you update your inline dependencies (i.e. FileSaver.js, etc.)? 
Do you have an unbuilt version of Datatables Buttons without the inline dependencies.  It would be useful to be able to build datatables and dt.buttons from scratch so end users can combine dependencies from multiple libraries into a single package and keep the dependencies updated with any bug fixes or changes while minimizing file/package sizes.

**Comment by DataTables** [comment]
They are updated whenever needed. There are own two inline dependencies - FileSaver and the Flash / Javascript bridge for the Flash version of the buttons. These were so fundamental to those button types and small that I just included them inline.

There is no option to not have them at the moment - other than to remove them from the source of course.

**Comment by DataTables** [comment]
Going to close this issue for now. I don't currently plan to remove FileSaver inline dependency, although it is something that I will keep in mind for future.
