### ISSUE TITLE
Better usage thru npm modules?

### ISSUE THREAD

**Issue by surfjedi** [DataTables/Buttons#83]
I am using this on a webpack/angular large application. It would be great if you could just npm install this, and then require it only once, instead of each file.

could this be an option if i fix and do a PR?

**Comment by DataTables** [comment]
Very interested. How would you do this with while keeping the button files optional (eg html5, flash and Clovis buttons, etc) without splitting each out into its own repo?

**Comment by surfjedi** [comment]
You would package as an npm module with an entry point index.js file, and possibly wrap the files in a module exports. maybe they need different verions. It's doable - angular, react and all those libraries do it.

Ill look into it more next week and get back to you

**Comment by DataTables** [comment]
The optional files are already wrapped up for export and can be included using `require()` with a direct reference to the file rather than to the module name.

Look forward to hearing what you find out.

**Comment by DataTables** [comment]
Going to close this for now as there is an npm module for Buttons: https://datatables.net/download/npm
