### ISSUE TITLE
Send proper content-type when exporting to Excel

### ISSUE THREAD

**Issue by jensadne** [DataTables/Buttons#85]
Currently Excel files are sent with content-type "application/octet-stream", which causes problems with certain browsers. Could this please be changed to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" which according to Microsoft is the correct MIME-type for those files? (see https://technet.microsoft.com/en-us/library/ee309278(office.12).aspx )

**Comment by DataTables** [comment]
Thanks - I'll get that fixed for the next release!

**Comment by DataTables** [comment]
Could you confirm what version of Buttons you are using please? The current release (1.1.2) should be [doing that already](https://github.com/DataTables/Buttons/blob/4bbaa1078226176d21601ff27870e9ab2c38bbf8/js/buttons.html5.js#L701).

What browser and OS are you using? I'm wondering how I can recreate the issue if you are using the current release?

**Comment by chipco** [comment]
Confirming it works fine in version 1.2.1

**Comment by DataTables** [comment]
Thanks - going to close this issue then.
