### ISSUE TITLE
Exclude column from export in Datatables Buttons

### ISSUE THREAD

**Issue by bhumiradixweb** [DataTables/Buttons#86]
How to exclude column from export in Datatables Buttons?

**Comment by DataTables** [comment]
Hi. This question and several like it have been asked in the forums if you use the site search there. [For example](https://www.datatables.net/forums/discussion/34743/).

See [this example](https://www.datatables.net/extensions/buttons/examples/html5/columns.html) for how to do it.

In future, can you ask support questions in the forums please, so there is a single searchable source for questions.
