### ISSUE TITLE
buttonLiner not available per-button

### ISSUE THREAD

**Issue by sronsiek** [DataTables/Buttons#87]
Using the buttons extension with multiple buttons, I would like to add button-specific glyphicons (a-la bootstrap). This is a property on the child span elements, which are be controlled via 

`buttons.dom.buttonLiner
`

Unfortunately this is not available on a per-button basis, so the icons on all buttons would be the same ...

**Comment by DataTables** [comment]
For icons, I would suggest [doing it this way](https://datatables.net/extensions/buttons/examples/styling/icons.html). Is that not suitable for your use case.

If not, you would need to use CSS with suitable selectors for the parent buttons. As you say `buttons.dom.buttonLiner` is a global setting, common to all buttons.

**Comment by sronsiek** [comment]
Thanks Alan! I couldn't quite work out where the images are defined in yr example - I guess it's here:

```
.fa-file-excel-o:before {
￼    content: "\f1c3";
}
```

But from yr example I saw I can nest html via the 'text' attribute, so I was able to solve this like this:

` text: '<span class="glyphicon glyphicon-download-alt"></span> CSV',`

This results in a span within a span - but works & looks as desired!
