### ISSUE TITLE
ES6 module import breaks buttons lib

### ISSUE THREAD

**Issue by sronsiek** [DataTables/Buttons#88]
In ES6, javascript libs are imported as modules via import statements. Hence JSZip would be included by:

` import JSZip from 'jszip/dist/jszip';`

However this scheme (deliberately) does not set global access to `window.JSZip`, which consequently causes code in the buttons-html5.js to mark the 'excel' button as unavailable:

```
available: function () {
    return window.FileReader !== undefined && window.JSZip !== undefined && ! _isSafari();
},

...

    var zip           = new window.JSZip();
```

Is it possible to use / provide the plugin without the need to inject the code into `window` ?

I have not checked, but I fear the same issue may be present with makePdf module & the PDF button.

**Comment by DataTables** [comment]
f497837a9b57e20bb4d8a8fd6a11a5f010f4a89f from yesterday will help in a CommonJS setting, but possibly not ES6 modules (I don't know enough about them to know how well they overlap).

**Comment by sronsiek** [comment]
Since after your change the lib no longer attaches the js to the window object, I think we can work with it!

Are you planning to release the modified code soon? Do you know how long it will take until an npm download becomes available?

**Comment by DataTables** [comment]
Should be out next week :-).
