### ISSUE TITLE
Print view doesn't work if (typeof data == 'number')

### ISSUE THREAD

**Issue by maslianok** [DataTables/Buttons#9]
Data for datatable:
```javascript
{
  {id: 1, name: 'John Doe'},
  {id: 2, name: 'Jane Doe'}
}
```
I've got an error when trying to print table:
```javascript
Uncaught TypeError: str.replace is not a function @ dataTables.buttons.js:1381
```
The problem is in `strip` function. You should check type of variable. For example:
```javascript
var strip = function ( str ) {
	if (typeof str == 'number') {
		return str;
	}
	/*...*/
};
```

**Comment by DataTables** [comment]
Hi,

This has been fixed by commit 4c5b2e5388434199f. I'll do a release at the end of this week with this fix and others.
