### ISSUE TITLE
buttons issues

### ISSUE THREAD

**Issue by satrianivzla** [DataTables/Buttons#90]
I am trying to use Buttons for DataTables 1.1.2 with UItoTop jQuery Plugin 1.2 and  I would like to know how should be changed to have the full number pagination, I tried to make it work but I can't find the correct way to do it.
Thank U in advance!

**Comment by DataTables** [comment]
[This example shows](https://datatables.net/examples/basic_init/alt_pagination.html) how to use the full numbers paging control.

I don't understand why any external plug-in would have any effect on the paging control in DataTables. I would need a link to a test case showing the issue please.

**Comment by satrianivzla** [comment]
I have no idea about it,  as you well said. Today I fixed rebuilding the custom data-tables file that I was trying to use yesterday ... using the same options and it works!

**Comment by satrianivzla** [comment]
As long as I see today  there is no problem and still working fine ...
`$(document).ready(function() {
	$().UItoTop({ easingType: 'easeOutQuart' });
 	$('#example').DataTable( {    
        "pagingType": "full_numbers",    
		dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );`

**Comment by DataTables** [comment]
Thanks for the update. Good to hear it is working now.
