### ISSUE TITLE
Colvis show hidden column in menu

### ISSUE THREAD

**Issue by lenamtl** [DataTables/Buttons#93]
Hi,

I think there is a  bug...

I'm wondering how come the colvis columns does not show visible item only into the menu list?
Let say
`
{
extend: 'colvis',
columns: ':visible',
}, 
`
and I have some **columnDefs** set to "visible": false,.

This will show hidden column into the colvis menu,
 the column name will not be pre-selected but it is selectable, if I click on it it will display the column.
I want to prevent that.

Here is the original discussion
https://datatables.net/forums/discussion/comment/95104#Comment_95104

**Comment by DataTables** [comment]
Going to close this and we'll keep the discussion in the forum, even if it is decided to be a bug.
