### ISSUE TITLE
Possible multiple buttons / button groups flexibility enhancement

### ISSUE THREAD

**Issue by legshooter** [DataTables/Buttons#94]
I'm using DataTables with Bootstrap 3, and whenever I specify multiple buttons they're automatically rendered in a `.btn-group`. I feel like this is much more of a design decision that better customizability should be provided for.

[As evident in the docs ](https://datatables.net/extensions/buttons/examples/initialisation/multiple.html), If I want each of the buttons rendered without a group, I have to keep `new`ing them up. So If I want a couple of `copy` and `pdf` default, regular, ungrouped buttons, as far as I know I can't do it by just setting a default, which is a shame.

I imagine something along the lines of:
```javascript
$.extend(true, $.fn.dataTable.defaults, {
  buttons: [
    [ 'copy' ], 
    [ 'pdf' ], 
  ]
)};
```

Same but customized:
```javascript
buttons: [
  [ 
    {
        text: "<span class='fa fa-refresh'></span>",
        action: function (e, dt, node, config) {
            dt.ajax.reload(null, false);
        }
    }    
  ], 
  [ 'csv' ], 
]
```
That way each could perhaps render a group surrounding itself, or none at all if only one button is provided in the sub array(?).

I obviously can go the route of overriding `.btn-group` CSS, but again, feels like another cumbersome alternative.

In my personal case a group just feels too condensed for mobile touch use, maybe even desktop use. I understand this can be a matter of personal taste though. I just wish I had more freedom by setting a flexible default and be done with it.

**Comment by DataTables** [comment]
```
$.fn.dataTables.Buttons.defailts.dom.container.className = 'dt-buttons';
```

should do it. The default value for that parameter is `dt-buttons btn-group`.

**Comment by DataTables** [comment]
Going to close this issue now based on the reaction :-)
