### ISSUE TITLE
Printing in tabs

### ISSUE THREAD

**Issue by wwalters** [DataTables/Buttons#96]
When the table that is being selected by the javascript is contained within a tab and is not the first tab in the list it seems to want to print a second page out that is blank save for headers and footers.

**Comment by DataTables** [comment]
Can you post issues and support requests [in the DataTables forums](//datatables.net/forums) and include a link to a test case showing the issue please?

**Comment by wwalters** [comment]
Couldn't get this page to load originally my appoligies, I will post it up
there.

On Thu, Jun 23, 2016 at 9:16 AM, Allan Jardine <notifications@github.com>
wrote:

> Can you post issues and support requests in the DataTables forums
> <//datatables.net/forums> and include a link to a test case showing the
> issue please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DataTables/Buttons/issues/96#issuecomment-228063869>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQyFc-TohBejJCu7b5b6m_J65yjCuyLLks5qOpVIgaJpZM4I82k3>
> .
>



-- 
-William Walters
