### ISSUE TITLE
Add option to pass custom data source for built-in export action

### ISSUE THREAD

**Issue by tuanpt216** [DataTables/Buttons#97]
Hi, 
I use Datatables with server-side processing. Follow [this example](https://datatables.net/examples/server_side/select_rows.html) I can remember the selected rows over pages.
Now I want to export the selected rows instead of the data which is got from: 
`var data = dt.buttons.exportData( config.exportOptions );`

Are there any existed solutions for this? I find an [example](https://datatables.net/extensions/buttons/examples/print/select.html) `modifier: { selected: true }` with the extension [Select](https://datatables.net/extensions/select/) but it does not support server side.
Can we have an option to pass custom data for export, that means we can build data that same structure with the data from `dt.buttons.exportData()` and pass it to button action? 

I think the option could be:
- **data**: _object_ or _function_
  - _object_: data object for export
  - _function_: function that can be used to build data for export. The value that the function returns is the value that will be used for the export.

Thanks!

**Comment by DataTables** [comment]
My apologies if the template text for the "new issue" wasn't clear - please post support requests in the [DataTables forums](//datatables.net/forums).

In the example you link to there is a `selected` array - you could use that since it contains the ids of the rows that were selected.

**Comment by tuanpt216** [comment]
Hi, I am requesting for adding new feature.

I had the `selected` data, but I can't find any option that I can pass that data to some default button, eg. [print](https://datatables.net/reference/button/print), [excelHtml5](https://datatables.net/reference/button/excelHtml5), [pdfHtml5](https://datatables.net/reference/button/pdfHtml5),... because the data is always got inside button action, eg. [buttons.html5.js](https://github.com/DataTables/Buttons/blob/master/js/buttons.html5.js): `var data = dt.buttons.exportData( config.exportOptions );`.
Moreover with the api [dt.buttons.exportData()](https://datatables.net/reference/api/buttons.exportData()) I cannot find a way to return the selected data since **row-selector**, **column-selector** does not work with server side datatables.

Any suggest? Thanks
`

**Comment by tuanpt216** [comment]
I just want to re-use exporting code, so I override function `buttons.exportData()` to pass custom data, which I get from selected row in tables with server side.
```Javascript
/*
 * Override Datatables Buttons Api buttons.exportData()
 * The original api source can be see at:
 * https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js
 * Add option: **customData** as a function
 */
$.fn.dataTable.Api.register('buttons.exportData()', function(options) {
  var dt = new $.fn.dataTable.Api(this.context[0]);
  var config = $.extend(true, {}, {
    columns: '',
  }, options);
  // Properties of object used to display in column
  var dataSrc = dt.columns(config.columns).dataSrc();
  // Get header title for each property
  var header = dt.columns(config.columns).indexes().map(function(idx) {
    return dt.column(idx).header().innerHTML;
  }).toArray();

  // data used for export
  var data = {
    header: header,
    body: [],
  };

  var dataSource = options.customData();
  if (!dataSource || $.isEmptyObject(dataSource)) {
    // All data => array of dataObject
    dataSource = dt.data();
  }
  for (var i = 0; i < dataSource.length; ++i) {
    var rowData = dataSource[i];
    var rowDataForExport = [];
    // Get only data of property which display in table
    for (var idx = 0; idx < dataSrc.length; ++idx) {
      var cellData = rowData[dataSrc[idx]];
      rowDataForExport.push(cellData);
    }
    data.body.push(rowDataForExport);
  }
  return data;
});
```

Then use in export option:
```Javascript
var exportOptions = {
  columns: ':not(.control-columns):not(.action-column)',
  customData: function() {
    // Global var
    return selectedRows.objects
  }
};
```

**Comment by DataTables** [comment]
Thanks for posting this - much appreciated, and I'm sure others will find it useful as well.
