### ISSUE TITLE
buttons.buttons.titleAttr to support i18n()

### ISSUE THREAD

**Issue by legshooter** [DataTables/Buttons#98]
Hey Allan,

Saw your reply in the [forums ](https://datatables.net/forums/discussion/36299/using-i18n-buttons-buttons-titleattr) and figured a GitHub issue will be easier to track.

Thanks.

**Comment by DataTables** [comment]
I'd prefer if we keep it in the forums actually - otherwise it means there are two places for it to be tracked and I'll forget to update one!

**Comment by legshooter** [comment]
Oh, I thought it's purely for usage support. Alrighty, you're the boss.
