### ISSUE TITLE
HTML5 Copy to clipboard fails on large datasets

### ISSUE THREAD

**Issue by simshaun** [DataTables/Buttons#99]
I've got a dataset with several thousand records that the Copy to clipboard button fails on.

I've set up an extreme example with 20k rows at http://codepen.io/simshaun/pen/rLvNyP

# Firefox
Console shows this:
> document.execCommand('cut'/'copy') was denied because it was not called from inside a short running user-generated event handler.

# Chrome
Fails silently

**Comment by simshaun** [comment]
Looks like this was fixed in https://github.com/DataTables/Buttons/commit/4dccc943253f5798b166e726e574c297f2fbb029

Any chance of tagging a new release soon?

**Comment by DataTables** [comment]
Had planned to today, but got side tracked. Probably Monday
